/* 行程資料集中在這裡：可直接修改日期、地點、時間、備註與金額。 */
const TRIP_DATA = {
  title: "關西，慢慢走",
  subtitle: "大阪 × 京都｜一趟留給街角與晚風的旅行",
  dateRange: "2026. 10. 11 — 10. 18",
  location: "日本關西 · 8 DAYS / 7 NIGHTS",
  description: "八天，把大阪的熱鬧與京都的安靜放進同一張地圖。早晨去看一座寺，傍晚沿著河走，剩下的交給當天的心情。",
  note: "十月關西早晚微涼；舒適步行鞋與輕薄外套優先。",
  days: [
    { id: "day-1", short: "11", weekday: "日", label: "桃園 → 關西 → 京都", summary: "清晨出發，經關西機場前往京都。", stops: [
      { time: "04:40", leave: "05:00", title: "台灣桃園第一航廈", place: "桃園國際機場第一航廈", type: "arrival", transport: "報到／登機", duration: "20 分鐘", note: "航班起飛前完成報到與行李託運。", cost: 0 },
      { time: "06:40", leave: "10:25", title: "抵達關西機場", place: "大阪府泉佐野市泉州空港北 1", type: "arrival", transport: "國際航班", duration: "3 小時 45 分鐘", note: "入境、領行李、購買交通票券。", cost: 0, links: [{ label: "KIX 航班資訊", url: "https://www.kansai-airport.or.jp/en/flight/search?direction=ARR" }] },
      { time: "10:25", leave: "10:55", title: "入境・領行李・購買交通票券", place: "關西國際機場第一航廈", type: "train", transport: "機場內步行", duration: "30 分鐘", note: "確認利木津巴士乘車位置與票券。", cost: 0, links: [{ label: "KIX 官方旅客資訊", url: "https://www.kansai-airport.or.jp/en/" }] },
      { time: "10:56", leave: "11:18", title: "利木津巴士候車・出發", place: "關西國際機場利木津巴士站", type: "train", transport: "利木津巴士", duration: "22 分鐘", note: "前往關西機場巴士乘車處。", cost: 0, links: [{ label: "KATE 巴士時刻表", url: "https://www.kate.co.jp/en/timetable/" }] },
      { time: "11:18", leave: "12:30", title: "利木津巴士（關西機場 → 京都站）", place: "京都站八條口", type: "train", transport: "利木津巴士", duration: "1 小時 12 分鐘", note: "抵達京都站後前往飯店寄放行李。", cost: 3600, links: [{ label: "京都線官方時刻表", url: "https://www.keihanbus.jp/limousine/kix/limousine_kanku_kyoto.html" }] },
      { time: "12:35", leave: "12:40", title: "unito hotel residence Kyoto Station・寄放行李（第一晚）", place: "京都府京都市下京區東鹽小路町 9-2", type: "stay", transport: "步行", duration: "5 分鐘", note: "第一天住宿；只寄放行李後立即離開，不辦理正式入住。", cost: 0 },
      { time: "13:00", leave: "14:10", title: "本家 第一旭 本店 拉麵", place: "京都府京都市下京區東鹽小路町 845", type: "food", transport: "步行", duration: "1 小時 10 分鐘", note: "京都站旁的第一餐。若排隊較久，彈性調整。", cost: 1200 },
      { time: "14:35", leave: "16:30", title: "京都高島屋 S.C.", place: "京都府京都市下京區四條通河原町西入真町 52", type: "shopping", transport: "阪急電鐵／步行", duration: "1 小時 55 分鐘", note: "逛街與採買。", cost: 0, links: [{ label: "阪急電鐵官方", url: "https://www.hankyu.co.jp/global/en/" }] },
      { time: "16:35", leave: "17:10", title: "ESP KYOTO (@espkyoto)", place: "京都府京都市中京區中之町 543-1", type: "shopping", transport: "步行", duration: "35 分鐘", note: "京都市 ESP KYOTO。", cost: 0 },
      { time: "17:20", leave: "18:20", title: "東寺（教王護國寺）", place: "京都府京都市南區九條町 1", type: "culture", transport: "電車／步行", duration: "1 小時", note: "第一天以參拜與散步收尾。", cost: 500, links: [{ label: "東寺官方交通", url: "https://toji.or.jp/en/location/index.html" }] }
    ]},
    { id: "day-2", short: "12", weekday: "一", label: "京都嵐山", summary: "搭上小火車，順著保津川慢慢下山。", stops: [
      { time: "06:30", leave: "07:00", title: "京都新阪急酒店（第二間飯店）", place: "京都府京都市下京區東鹽小路町 579", type: "stay", transport: "步行", duration: "30 分鐘", note: "第二天使用的不同飯店；與第一天的 unito hotel residence Kyoto Station 不同。早餐／出發準備。", cost: 0 },
      { time: "07:10", leave: "07:30", title: "JR 京都站", place: "京都府京都市下京區東鹽小路町", type: "train", transport: "步行／JR 嵯峨野線", duration: "20 分鐘", note: "建議搭 07:34 左右往龜岡方向的普通／快速列車，前往 JR 嵯峨嵐山站。", cost: 240, links: [{ label: "JR West 路線・時刻表", url: "https://www.westjr.co.jp/global/en/timetable/search_jp/" }] },
      { time: "07:34", leave: "07:59", title: "JR 嵯峨嵐山站（要轉搭小火車）", place: "京都府京都市右京區嵯峨天龍寺車道町 11-1", type: "train", transport: "JR 山陰本線", duration: "25 分鐘", note: "抵達後步行轉往嵯峨野觀光小火車嵯峨站。", cost: 240, links: [{ label: "JR West 路線・時刻表", url: "https://www.westjr.co.jp/global/en/timetable/search_jp/" }] },
      { time: "08:30", leave: "08:55", title: "嵯峨野觀光小火車（嵯峨 → 龜岡）", place: "嵯峨野觀光鐵道 嵯峨站", type: "train", transport: "嵯峨野觀光小火車", duration: "25 分鐘", note: "沿保津川欣賞山谷景色；車次與座位以預約頁為準。", cost: 880, links: [{ label: "官方時刻表／預約", url: "https://www.sagano-kanko.co.jp/en/index.php/" }] },
      { time: "09:00", leave: "09:20", title: "步行至保津川遊船乘船處", place: "京都府龜岡市篠町山本地區", type: "nature", transport: "步行", duration: "約 15–20 分鐘", note: "依現場動線前往乘船處。", cost: 0 },
      { time: "09:20", leave: "09:30", title: "保津川遊船報到", place: "保津川遊船乘船場", type: "nature", transport: "步行", duration: "10 分鐘", note: "建議提前 10 分鐘完成報到；出航時間依官方當日安排。", cost: 0, links: [{ label: "官方時刻表", url: "https://www.hozugawakudari.jp/service/timetable" }] },
      { time: "09:30", leave: "11:30", title: "保津川遊船（出發）", place: "保津川遊船乘船場", type: "nature", transport: "保津川遊船", duration: "2 小時", note: "2026/10/12 為週一，官方資料顯示平日 09:00–15:00 每小時定期運航；仍請出發前確認。", cost: 6000, links: [{ label: "官方時刻表", url: "https://www.hozugawakudari.jp/service/timetable" }] },
      { time: "11:30", leave: "11:40", title: "抵達嵐山渡船口／渡月橋附近", place: "京都府京都市右京區嵯峨中之島町", type: "nature", transport: "步行", duration: "10 分鐘", note: "下船後前往午餐。", cost: 0 },
      { time: "11:45", leave: "12:25", title: "Wagyu Volcano Steak OAGARI（午餐）", place: "京都府京都市右京區嵯峨天龍寺芒之馬場町 3-25", type: "food", transport: "步行", duration: "40 分鐘", note: "午餐預約與候位依現場狀況。", cost: 4500 },
      { time: "12:35", leave: "13:00", title: "京都嵐山 和牛六重樓", place: "京都府京都市右京區嵯峨天龍寺芒之馬場町 3-25", type: "food", transport: "步行", duration: "25 分鐘", note: "與 Wagyu Volcano Steak OAGARI 為不同餐廳，兩間都要吃；此站安排快速用餐／品嚐。10:00 開門。", cost: 1500 },
      { time: "13:15", leave: "13:40", title: "天龍寺", place: "京都府京都市右京區嵯峨天龍寺芒之馬場町 68", type: "culture", transport: "步行", duration: "25 分鐘", note: "參觀庭園與法堂。", cost: 1000 },
      { time: "13:40", leave: "14:00", title: "竹林小徑", place: "京都府京都市右京區嵯峨天龍寺芒之馬場町", type: "nature", transport: "步行", duration: "20 分鐘", note: "避開人潮，沿主要步道散步。", cost: 0 },
      { time: "14:00", leave: "14:20", title: "野宮神社", place: "京都府京都市右京區嵯峨野宮町 1", type: "culture", transport: "步行", duration: "20 分鐘", note: "竹林小徑旁順路參拜。", cost: 0 },
      { time: "14:20", leave: "14:50", title: "祇王寺（推薦）或常寂光寺（二選一）", place: "京都府京都市右京區嵯峨鳥居本小坂町 32", type: "culture", transport: "步行", duration: "30 分鐘", note: "依體力與時間二選一。", cost: 500 },
      { time: "14:50", leave: "15:20", title: "嵐山商店街", place: "京都府京都市右京區嵯峨天龍寺造路町", type: "shopping", transport: "步行", duration: "30 分鐘", note: "伴手禮與街邊小吃。", cost: 2000 },
      { time: "15:30", leave: "16:00", title: "渡月橋・桂川散步", place: "京都府京都市右京區嵯峨中之島町", type: "nature", transport: "步行", duration: "30 分鐘", note: "嵐山行程收尾。", cost: 0 },
      { time: "16:00", leave: "", title: "返回京都市區", place: "京都市區", type: "train", transport: "JR／阪急電車", duration: "彈性", note: "圖片未提供離開時間，依當日體力與晚餐安排調整。", cost: 500, links: [{ label: "JR West 時刻表", url: "https://www.westjr.co.jp/global/en/timetable/search_jp/" }, { label: "阪急電鐵官方", url: "https://www.hankyu.co.jp/global/en/" }] }
    ]},
    { id: "day-3", short: "13", weekday: "二", label: "清水寺・祇園・伏見稻荷", summary: "從清晨的清水坂，走到祇園的夜色。", stops: [
      { time: "06:30", leave: "06:50", title: "JR 京都站", place: "京都府京都市下京區東鹽小路町", type: "train", transport: "JR／公車", duration: "20 分鐘", note: "清晨出發前往清水寺。", cost: 300, links: [{ label: "京都市交通資訊", url: "https://www2.city.kyoto.lg.jp/koho/eng/access/transport.html" }] },
      { time: "07:01", leave: "07:25", title: "清水寺", place: "京都府京都市東山區清水 1-294", type: "culture", transport: "公車／步行", duration: "24 分鐘", note: "趁早參拜，避開上午人潮。", cost: 500, links: [{ label: "Google Maps 導航", url: "https://www.google.com/maps/search/?api=1&query=清水寺" }] },
      { time: "08:20", leave: "08:40", title: "二年坂、三年坂慢慢逛、咖啡、伴手禮", place: "京都府京都市東山區二年坂、三年坂", type: "shopping", transport: "步行", duration: "20 分鐘", note: "留時間拍照、喝咖啡與採買伴手禮。", cost: 2500 },
      { time: "10:50", leave: "11:00", title: "京都府京都市東山区桜屋町349-18", place: "京都府京都市東山区桜屋町349-18", type: "cafe", transport: "步行", duration: "10 分鐘", note: "圖片提供的地址，店名待補。", cost: 0, links: [{ label: "Google Maps 導航", url: "https://maps.app.goo.gl/1EhoR2rPJD8HhfBF9" }] },
      { time: "12:30", leave: "12:40", title: "PORTER STAND 京都", place: "京都府京都市下京區東鹽小路町", type: "shopping", transport: "步行／電車", duration: "10 分鐘", note: "京都站周邊採買。", cost: 0 },
      { time: "13:00", leave: "13:15", title: "祇園四条站", place: "京都府京都市東山區四條大橋東詰", type: "train", transport: "京阪本線", duration: "15 分鐘", note: "由京都站方向前往祇園。", cost: 300, links: [{ label: "京阪電車官方", url: "https://www.keihan.co.jp/traffic/station/" }] },
      { time: "14:00", leave: "15:00", title: "伏見稻荷大社（神樂鈴）", place: "京都府京都市伏見區深草藪之內町 68", type: "culture", transport: "JR／京阪電車", duration: "1 小時", note: "參拜與體驗神樂鈴。", cost: 500, links: [{ label: "JR West 路線・時刻表", url: "https://www.westjr.co.jp/global/en/timetable/search_jp/" }] },
      { time: "15:30", leave: "15:50", title: "回祇園", place: "京都府京都市東山區祇園", type: "train", transport: "京阪電車／步行", duration: "20 分鐘", note: "返回祇園一帶。", cost: 300, links: [{ label: "京阪電車官方", url: "https://www.keihan.co.jp/traffic/station/" }] },
      { time: "16:30", leave: "17:00", title: "八阪神社（神樂鈴）", place: "京都府京都市東山區祇園町北側 625", type: "culture", transport: "步行", duration: "30 分鐘", note: "參拜八阪神社與體驗神樂鈴。", cost: 0 },
      { time: "18:00", leave: "18:20", title: "祇園四条公車站／京阪本線", place: "祇園四条站", type: "train", transport: "公車／京阪本線", duration: "20 分鐘", note: "原表格離開時間 13:07 與抵達時間矛盾，先往後調整為 18:20。", cost: 300, links: [{ label: "京都市交通資訊", url: "https://www2.city.kyoto.lg.jp/koho/eng/access/transport.html" }, { label: "京阪電車官方", url: "https://www.keihan.co.jp/traffic/station/" }] }
    ]},
    { id: "day-4", short: "14", weekday: "三", label: "京都逛街地點計劃中", summary: "沿著烏丸線與京都老街，慢慢走到錦市場。", stops: [
      { time: "07:40", leave: "08:00", title: "京都車站（地下鐵烏丸線）", place: "京都府京都市下京區東鹽小路町", type: "train", transport: "京都地下鐵烏丸線", duration: "20 分鐘", note: "搭乘烏丸線前往今出川站。", cost: 260, links: [{ label: "京都市地下鐵／公車", url: "https://www2.city.kyoto.lg.jp/koho/eng/access/transport.html" }] },
      { time: "08:03", leave: "08:12", title: "今出川站", place: "京都府京都市上京區岡松町", type: "train", transport: "地下鐵烏丸線", duration: "9 分鐘", note: "出站後步行前往晴明神社。", cost: 0, links: [{ label: "京都市交通資訊", url: "https://www2.city.kyoto.lg.jp/koho/eng/access/transport.html" }] },
      { time: "08:20", leave: "09:00", title: "晴明神社", place: "京都府京都市上京區晴明町 806", type: "culture", transport: "步行", duration: "40 分鐘", note: "參拜與拍攝五芒星社紋。", cost: 0 },
      { time: "09:05", leave: "09:50", title: "京都御苑", place: "京都府京都市上京區京都御苑", type: "nature", transport: "步行", duration: "45 分鐘", note: "在御苑內散步，感受早晨的安靜。", cost: 0 },
      { time: "10:10", leave: "10:50", title: "二條城", place: "京都府京都市中京區二條城町 541", type: "culture", transport: "步行／公車", duration: "40 分鐘", note: "參觀唐門與二之丸御殿。", cost: 1300 },
      { time: "11:15", leave: "12:30", title: "午餐（烏丸御池）", place: "京都府京都市中京區烏丸御池周邊", type: "food", transport: "步行／公車", duration: "1 小時 15 分鐘", note: "午餐店家待補；先保留用餐時段。", cost: 2500 },
      { time: "12:35", leave: "12:45", title: "VIVOBAREFOOT KYOTO", place: "京都府京都市中京區烏丸御池周邊", type: "shopping", transport: "步行", duration: "10 分鐘", note: "鞋款試穿與購物。", cost: 0 },
      { time: "13:00", leave: "13:10", title: "APFR KYOTO", place: "京都府京都市中京區京都市中心", type: "shopping", transport: "步行", duration: "10 分鐘", note: "香氛與生活用品。", cost: 0 },
      { time: "13:20", leave: "13:30", title: "六角堂", place: "京都府京都市中京區堂之前町 248", type: "culture", transport: "步行", duration: "10 分鐘", note: "順路參拜六角堂。", cost: 0 },
      { time: "13:50", leave: "14:00", title: "寺町通商店街", place: "京都府京都市中京區寺町通", type: "shopping", transport: "步行", duration: "10 分鐘", note: "逛京都市中心商店街。", cost: 0 },
      { time: "14:05", leave: "14:10", title: "新京極商店街", place: "京都府京都市中京區新京極通", type: "shopping", transport: "步行", duration: "5 分鐘", note: "與寺町通連續逛街。", cost: 0 },
      { time: "15:00", leave: "15:20", title: "錦市場", place: "京都府京都市中京區錦小路通", type: "food", transport: "步行", duration: "20 分鐘", note: "小吃與市場採買；依人潮彈性停留。", cost: 2200 }
    ]},
    { id: "day-5", short: "15", weekday: "四", label: "京都去大阪", summary: "退房後前往勝尾寺，再從千里中央一路走進難波與心齋橋。", stops: [
      { time: "07:45", leave: "08:00", title: "京都站／退房", place: "京都站", type: "stay", transport: "步行", duration: "15 分鐘", note: "退房、確認行李與交通票券。", cost: 0 },
      { time: "08:00", leave: "08:30", title: "JR 新快速 → 大阪站", place: "京都站 → 大阪站", type: "train", transport: "JR 京都線・新快速", duration: "30 分鐘", note: "前往大阪站，再轉御堂筋線。", cost: 580, links: [{ label: "JR West 路線・時刻表", url: "https://www.westjr.co.jp/global/en/timetable/search_jp/" }] },
      { time: "08:30", leave: "08:45", title: "大阪站 → 千里中央（御堂筋線）", place: "大阪 Metro 梅田站 → 千里中央站", type: "train", transport: "Osaka Metro 御堂筋線／北大阪急行", duration: "15 分鐘", note: "依指示轉乘北大阪急行線往千里中央。", cost: 430, links: [{ label: "Osaka Metro 官方", url: "https://subway.osakametro.co.jp/en/" }] },
      { time: "08:45", leave: "09:05", title: "千里中央 → 勝尾寺（阪急巴士）", place: "千里中央站巴士站 → 勝尾寺", type: "train", transport: "阪急巴士", duration: "20 分鐘", note: "確認當日巴士月台與發車時間；班次可能因日期調整。", cost: 500, links: [{ label: "阪急巴士官方", url: "https://www.hankyubus.co.jp/rosen/" }] },
      { time: "09:05", leave: "10:00", title: "勝尾寺", place: "大阪府箕面市勝尾寺", type: "culture", transport: "步行", duration: "55 分鐘", note: "參拜勝運達摩與庭園。", cost: 500, links: [{ label: "Google Maps 導航", url: "https://www.google.com/maps/search/?api=1&query=勝尾寺" }] },
      { time: "10:30", leave: "11:05", title: "勝尾寺 → 千里中央", place: "勝尾寺 → 千里中央站", type: "train", transport: "阪急巴士", duration: "35 分鐘", note: "回到千里中央轉往難波。", cost: 500, links: [{ label: "阪急巴士官方", url: "https://www.hankyubus.co.jp/rosen/" }] },
      { time: "11:05", leave: "11:35", title: "千里中央 → 難波", place: "千里中央站 → 難波站", type: "train", transport: "北大阪急行／Osaka Metro 御堂筋線", duration: "30 分鐘", note: "抵達難波後先用餐，再開始市區散步。", cost: 430, links: [{ label: "Osaka Metro 官方", url: "https://subway.osakametro.co.jp/en/" }] },
      { time: "11:40", leave: "12:10", title: "難波八阪神社", place: "大阪府大阪市浪速區元町 2-9-19", type: "culture", transport: "步行", duration: "30 分鐘", note: "原圖列在午餐後，但時間顯示 11:40–12:10；依時間順序先安排參拜。", cost: 0 },
      { time: "12:15", leave: "13:15", title: "午餐（難波）", place: "大阪府大阪市中央區難波周邊", type: "food", transport: "步行", duration: "1 小時", note: "難波午餐店家待補。", cost: 2500 },
      { time: "14:30", leave: "16:00", title: "道頓堀", place: "大阪府大阪市中央區道頓堀", type: "nature", transport: "步行", duration: "1.5 小時", note: "固力果跑跑人、戎橋與河畔散步。", cost: 0 },
      { time: "16:00", leave: "18:00", title: "心齋橋商店街", place: "大阪府大阪市中央區心齋橋筋", type: "shopping", transport: "步行", duration: "2 小時", note: "服飾、藥妝與伴手禮；當晚住宿大阪，住宿地點待補。", cost: 5000 }
    ]},
    { id: "day-6", short: "16", weekday: "五", label: "任天堂世界", summary: "今天的唯一主線：SUPER NINTENDO WORLD。", stops: [
      { time: "07:00", leave: "07:45", title: "前往 Universal Studios Japan", place: "大阪府大阪市此花區櫻島 2-1-33", type: "train", transport: "JR 環狀線 → 夢咲線／Universal City", duration: "45 分鐘", note: "建議提早抵達；實際開園時間可能早於公告，前一天確認官方日曆。", cost: 400, links: [{ label: "USJ 官方網站", url: "https://www.usj.co.jp/web/en/us/" }, { label: "JR West 路線・時刻表", url: "https://www.westjr.co.jp/global/en/timetable/search_jp/" }] },
      { time: "07:45", leave: "08:15", title: "入園前準備：票券與官方 App", place: "Universal Studios Japan 大門", type: "fun", transport: "步行／排隊", duration: "30 分鐘", note: "前一晚先下載 USJ 官方 App、登入帳號、把所有同行者 Studio Pass QR code 加入 App，手機充飽並準備行動電源。不要在入園後才開始下載。", cost: 0, links: [{ label: "官方 App 說明", url: "https://www.usj.co.jp/web/en/us/enjoy/app?hideToolbar=false" }, { label: "電子整理券說明", url: "https://www.usj.co.jp/web/en/us/enjoy/numbered-ticket" }] },
      { time: "08:15", leave: "09:00", title: "SUPER NINTENDO WORLD 入場安排", place: "SUPER NINTENDO WORLD™, Universal Studios Japan", type: "fun", transport: "園區內步行", duration: "45 分鐘", note: "入園後第一件事：看 App 是否能取得 Area Timed Entry Ticket；若快速通關已含指定時段就依票券入場。所有同行者票券先登錄，避免到現場才處理。", cost: 0, links: [{ label: "官方入場券說明", url: "https://www.usj.co.jp/web/en/us/enjoy/numbered-ticket/timed-entry-ticket" }, { label: "官方 App／整理券", url: "https://www.usj.co.jp/web/en/us/enjoy/numbered-ticket/app/timed-entry-ticket" }] },
      { time: "09:00", leave: "10:30", title: "Mario Kart: Koopa's Challenge", place: "SUPER NINTENDO WORLD™, Universal Studios Japan", type: "fun", transport: "園區內步行", duration: "1.5 小時", note: "任天堂主線第一順位；先玩最想玩的 Mario Kart，再看現場等待時間調整。", cost: 0, links: [{ label: "官方園區地圖／設施", url: "https://www.usj.co.jp/web/en/us/park-guide/" }] },
      { time: "10:30", leave: "12:00", title: "Yoshi's Adventure・園區探索", place: "SUPER NINTENDO WORLD™, Universal Studios Japan", type: "fun", transport: "園區內步行", duration: "1.5 小時", note: "第二順位玩 Yoshi；沿途拍照、找互動裝置。若排隊過長，改成先逛 1-UP Factory 與角色拍照。", cost: 0 },
      { time: "12:00", leave: "13:15", title: "Kinopio's Café 午餐", place: "SUPER NINTENDO WORLD™, Universal Studios Japan", type: "food", transport: "園區內步行", duration: "1 小時 15 分鐘", note: "想吃主題餐點就優先確認入場方式；熱門時段可能需要排隊，必要時改園區其他餐廳。", cost: 2800 },
      { time: "13:15", leave: "14:15", title: "1-UP Factory・任天堂商店", place: "SUPER NINTENDO WORLD™, Universal Studios Japan", type: "shopping", transport: "園區內步行", duration: "1 小時", note: "集中購買任天堂限定商品；Power-Up Band 是否購買可到現場再決定。", cost: 0 },
      { time: "14:15", leave: "15:00", title: "Power-Up Band 互動任務（可選）", place: "SUPER NINTENDO WORLD™, Universal Studios Japan", type: "fun", transport: "園區內步行", duration: "45 分鐘", note: "如果想完成園區互動任務，再購買 Power-Up Band；不買也不影響主要設施體驗。", cost: 4500 },
      { time: "15:00", leave: "17:30", title: "任天堂世界補拍・重玩", place: "SUPER NINTENDO WORLD™, Universal Studios Japan", type: "fun", transport: "園區內步行", duration: "2.5 小時", note: "回頭補拍照、角色活動或重玩等待時間較短的設施；這段保留給現場變化。", cost: 0 },
      { time: "17:30", leave: "19:30", title: "離開任天堂世界・其他區域備選", place: "Universal Studios Japan", type: "fun", transport: "園區內步行", duration: "2 小時", note: "任天堂完成後才考慮其他園區；依體力選 1–2 項，不再安排跨園區衝刺。", cost: 0, links: [{ label: "USJ 官方最新公告", url: "https://www.usj.co.jp/web/en/us/park-guide/schedule/" }] },
      { time: "19:30", leave: "20:30", title: "離園・返回住宿地", place: "Universal City Station", type: "train", transport: "JR 夢咲線 → JR 環狀線", duration: "1 小時", note: "離園時間依當日活動與體力調整；避開散場人潮可先在 CityWalk 用餐。", cost: 400, links: [{ label: "JR West 路線・時刻表", url: "https://www.westjr.co.jp/global/en/timetable/search_jp/" } ] }
    ]},
    { id: "day-7", short: "17", weekday: "六", label: "大阪在地生活＋購物", summary: "從市場早餐開始，走過天神橋與北濱，最後逛梅田。", stops: [
      { time: "07:40", leave: "", title: "飯店出發", place: "大阪市區住宿地", type: "train", transport: "大阪 Metro／步行", duration: "彈性", note: "圖片只有抵達時間欄；實際出發時間以住宿地點與交通狀況調整。", cost: 300, links: [{ label: "Osaka Metro 官方", url: "https://subway.osakametro.co.jp/en/" }] },
      { time: "08:00", leave: "", title: "木津市場", place: "大阪府大阪市浪速區敷津東 2-2-8", type: "food", transport: "大阪 Metro／步行", duration: "彈性", note: "市場早餐與在地食材；建議先吃早午餐再逛。", cost: 1800, links: [{ label: "Google Maps 導航", url: "https://www.google.com/maps/search/?api=1&query=大阪木津市場" }] },
      { time: "09:30", leave: "", title: "木津市場 → 扇町站（大阪 Metro）", place: "扇町站（大阪 Metro）", type: "train", transport: "大阪 Metro", duration: "彈性", note: "由木津市場前往扇町；實際搭乘路線以當日 App 查詢為準。", cost: 240, links: [{ label: "Osaka Metro 官方", url: "https://subway.osakametro.co.jp/en/" }] },
      { time: "10:00", leave: "", title: "SAKImotobakery and more 扇町店", place: "大阪府大阪市北區天神橋 3-7-13 プラーヴォ扇町 1F", type: "cafe", transport: "步行", duration: "彈性", note: "苫本ベーカリーandmore 扇町店；麵包、早餐與咖啡。", cost: 1200, links: [{ label: "Google Maps 導航", url: "https://www.google.com/maps/search/?api=1&query=SAKImotobakery%20and%20more%20扇町店" }] },
      { time: "11:00", leave: "", title: "天神橋筋商店街", place: "大阪府大阪市北區天神橋筋商店街", type: "shopping", transport: "步行", duration: "彈性", note: "日本最長商店街之一；適合邊走邊吃、慢慢逛。", cost: 2500 },
      { time: "12:30", leave: "", title: "午餐", place: "大阪府大阪市北區天神橋周邊", type: "food", transport: "步行", duration: "彈性", note: "午餐店家待補；保留在天神橋筋附近用餐。", cost: 2500 },
      { time: "13:35", leave: "", title: "大阪天滿宮", place: "大阪府大阪市北區天神橋 2-1-8", type: "culture", transport: "步行", duration: "彈性", note: "參拜與散步。", cost: 0 },
      { time: "14:20", leave: "", title: "中之島公園／北濱咖啡街", place: "大阪府大阪市北區中之島 1 丁目", type: "cafe", transport: "大阪 Metro／步行", duration: "彈性", note: "咖啡、河畔散步；依體力安排停留。", cost: 1200, links: [{ label: "大阪觀光官方", url: "https://osaka-info.jp/en/" }] },
      { time: "15:20", leave: "", title: "前往梅田", place: "大阪梅田站", type: "train", transport: "大阪 Metro／步行", duration: "彈性", note: "由北濱方向前往梅田購物區。", cost: 240, links: [{ label: "Osaka Metro 官方", url: "https://subway.osakametro.co.jp/en/" }] },
      { time: "15:35", leave: "", title: "Grand Front Osaka", place: "大阪府大阪市北區大深町 4-1", type: "shopping", transport: "步行", duration: "彈性", note: "梅田第一站購物。", cost: 0 },
      { time: "16:30", leave: "", title: "LUCUA Osaka", place: "大阪府大阪市北區梅田 3-1-3", type: "shopping", transport: "步行", duration: "彈性", note: "服飾、生活雜貨與伴手禮。", cost: 0 },
      { time: "17:15", leave: "", title: "Yodobashi Umeda", place: "大阪府大阪市北區大深町 1-1", type: "shopping", transport: "步行", duration: "彈性", note: "電器、藥妝與最後採買。", cost: 0 },
      { time: "18:20", leave: "", title: "晚餐（梅田）", place: "大阪府大阪市北區梅田周邊", type: "food", transport: "步行", duration: "彈性", note: "梅田晚餐店家待補。", cost: 3500 }
    ]},
    { id: "day-8", short: "18", weekday: "日", label: "回祖國", summary: "最後採買、臨空城，再搭晚班機回家。", stops: [
      { time: "08:00", leave: "09:00", title: "早餐／Check out", place: "大阪市區住宿地", type: "stay", transport: "步行", duration: "1 小時", note: "退房、確認行李與護照。", cost: 0 },
      { time: "09:10", leave: "10:20", title: "難波咖啡廳（Brooklyn Roasting × Lilo Coffee × Arabica 等）", place: "大阪府大阪市中央區難波周邊", type: "cafe", transport: "步行", duration: "1 小時 10 分鐘", note: "最後一杯咖啡與早餐。", cost: 1800 },
      { time: "10:30", leave: "12:00", title: "美國村（古著、潮流服飾、咖啡）", place: "大阪府大阪市中央區西心齋橋 2 丁目", type: "shopping", transport: "大阪 Metro／步行", duration: "1.5 小時", note: "最後採買；注意行李容量。", cost: 5000, links: [{ label: "Osaka Metro 官方", url: "https://subway.osakametro.co.jp/en/" }] },
      { time: "12:00", leave: "13:00", title: "午餐", place: "大阪市區／心齋橋周邊", type: "food", transport: "步行", duration: "1 小時", note: "午餐店家待補。", cost: 2500 },
      { time: "13:00", leave: "15:30", title: "臨空城 Premium Outlets", place: "大阪府泉佐野市りんくう往来南 3-28", type: "shopping", transport: "南海電鐵／步行", duration: "2.5 小時", note: "如果搭南海電鐵前往關西機場，可先在臨空城下車購物，再前往機場。", cost: 0, links: [{ label: "Rinku Premium Outlets 官方", url: "https://www.premiumoutlets.co.jp/chs/rinku/" }, { label: "南海電鐵官方", url: "https://www.nankai.co.jp/en_railway/" }] },
      { time: "15:40", leave: "16:00", title: "臨空城 → 關西機場", place: "關西國際機場", type: "train", transport: "南海電鐵／機場線", duration: "20 分鐘", note: "前往機場辦理報到。", cost: 500, links: [{ label: "南海電鐵官方", url: "https://www.nankai.co.jp/en_railway/" }] },
      { time: "16:00", leave: "20:55", title: "關西機場（退稅、托運、免稅店、晚餐）", place: "大阪府泉佐野市泉州空港北 1", type: "arrival", transport: "機場內步行", duration: "4 小時 55 分鐘", note: "辦理退稅、托運、安檢與免稅店；晚餐留在機場解決。", cost: 2500, links: [{ label: "關西機場官方", url: "https://www.kansai-airport.or.jp/en/" }] },
      { time: "20:55", leave: "23:05", title: "其他旅客｜亞洲航空", place: "關西機場 → 桃園機場", type: "arrival", transport: "亞洲航空", duration: "2 小時 10 分鐘", note: "其他旅客（包含和學）搭乘的回程航班，與 Emma 的航班不同。航班編號待補。", cost: 0 },
      { time: "13:25", leave: "15:20", title: "Emma｜星宇航空", place: "關西機場 → 桃園機場", type: "arrival", transport: "星宇航空", duration: "1 小時 55 分鐘", note: "Emma 搭乘的回程航班，與其他旅客為不同班機。航班編號待補。", cost: 0 }
    ]}
  ],
  budget: [
    { label: "交通", key: "transport", amount: 12000, icon: "↝", tone: "blue" },
    { label: "餐費", key: "food", amount: 24000, icon: "⌁", tone: "orange" },
    { label: "購物／彈性", key: "shopping", amount: 18000, icon: "✳", tone: "green" }
  ],
  reminders: [
    { title: "入境前｜Visit Japan Web", text: "先完成入境與海關資料，將 QR code 截圖並保存在離線相簿；護照姓名、航班與住宿資料要完全一致。", links: [{ label: "官方入境服務", url: "https://www.digital.go.jp/en/policies/visit_japan_web" }] },
    { title: "交通日｜先看官方班次", text: "JR、地下鐵、巴士與觀光列車都要在出發前再查一次；不要只依賴行程表上的預估時間。", links: [{ label: "JR West 時刻表", url: "https://www.westjr.co.jp/global/en/timetable/search_jp/" }] },
    { title: "京都｜尊重街區與寺社", text: "祇園不要進入私人道路或住宅區；不擋路、不追拍、不邊走邊吃，垃圾帶走。", links: [{ label: "京都官方禮儀", url: "https://kyoto.travel/en/responsible-travel/mind-your-manners/" }] },
    { title: "USJ 前一晚", text: "更新官方 App、把所有 Studio Pass 登錄進去、準備行動電源；入園後先處理 SUPER NINTENDO WORLD 的整理券／預約。", links: [{ label: "USJ 官方 App／整理券", url: "https://www.usj.co.jp/web/en/us/enjoy/numbered-ticket/app/timed-entry-ticket" }] },
    { title: "嵐山日｜觀光列車與遊船", text: "嵯峨野小火車、保津川遊船的班次與開航會受日期、天候與現場狀況影響；預約與出發前再次確認。", links: [{ label: "嵯峨野觀光鐵道", url: "https://www.sagano-kanko.co.jp/en/index.php/" }, { label: "保津川遊船時刻表", url: "https://www.hozugawakudari.jp/service/timetable" }] },
    { title: "住宿與行李", text: "第一天 unito 是寄放行李後離開，不是正式入住；第二天是不同的京都新阪急酒店。10/15 晚上改住大阪，住宿地址仍要補入。" },
    { title: "交通轉乘", text: "車站月台、出口與巴士站可能需要步行時間；預留至少 10–15 分鐘轉乘，看到『建議搭乘』不代表已完成訂位。" },
    { title: "餐廳與排隊", text: "第一旭、嵐山兩間和牛餐廳、USJ 餐廳與熱門咖啡店都可能排隊；預約、候位與替代店家要事先想好。" },
    { title: "寺社與街區禮儀", text: "寺社內保持安靜、依規定參拜；祇園與住宅街不要進入私人道路、不追拍工作人員或居民，拍照先看現場標示。", links: [{ label: "京都官方禮儀", url: "https://kyoto.travel/en/responsible-travel/mind-your-manners/" }] },
    { title: "購物與退稅", text: "退稅商品、護照與收據要妥善保存；購物前確認店家是否提供免稅、商品是否需要密封，以及回程托運／手提限制。" },
    { title: "支付與網路", text: "交通 IC 卡、信用卡與現金分開準備；重要 QR code、住宿地址、航班與地圖截圖離線保存，避免完全依賴網路。" },
    { title: "天候與戶外行程", text: "嵐山、勝尾寺、USJ、京都御苑與保津川都是戶外行程；雨具、防滑鞋、替換襪與薄外套放在隨身包，遊船若停航要以官方公告為準。" },
    { title: "每天晚上", text: "確認隔日第一班車、天氣、電量、現金、交通 IC 卡、票券 QR code 與集合時間。" },
    { title: "回程日", text: "退稅、托運、安檢與登機時間要分開預留；不同旅客的航班不要共用同一個離場時間。" }
  ],
  checklist: [
    { id: "passport", text: "護照／Visit Japan Web／入境資料" },
    { id: "tickets", text: "機票、住宿、JR／巴士／觀光列車票券" },
    { id: "usj", text: "USJ App、Studio Pass QR code、整理券規則" },
    { id: "power", text: "行動電源、充電線、轉接頭與離線截圖" },
    { id: "money", text: "日圓、信用卡、交通 IC 卡與備用現金" },
    { id: "weather", text: "薄外套、雨具、舒適步行鞋與替換襪" },
    { id: "medicine", text: "常備藥、處方箋／藥袋與個人用品" },
    { id: "luggage", text: "行李重量、退稅商品、液體與伴手禮空間" },
    { id: "contacts", text: "同行者聯絡方式、住宿地址、保險資料" },
    { id: "flight", text: "Emma／星宇、其他旅客／亞洲航空分開確認" }
  ],
  emergency: [
    { label: "日本警察", value: "110", action: "tel:110" },
    { label: "日本消防／救護車", value: "119", action: "tel:119" },
    { label: "日本外務省旅外安全", value: "安全資訊網站", action: "https://www.anzen.mofa.go.jp/" },
    { label: "駐大阪辦事處", value: "官方聯絡資料", action: "https://www.mofa.gov.tw/OverseasOffice_Content.aspx?n=168&os=85&s=142&sms=87" },
    { label: "住宿／保險／同行者", value: "請補上個人資料", action: "#" }
  ]
};
