/* 行程資料集中在這裡：可直接修改日期、地點、時間、備註與金額。 */
const TRIP_DATA = {
  title: "關西，慢慢走",
  subtitle: "大阪 × 京都｜一趟留給街角與晚風的旅行",
  dateRange: "2026. 10. 11 — 10. 18",
  location: "日本關西 · 8 DAYS / 7 NIGHTS",
  description: "八天，把大阪的熱鬧與京都的安靜放進同一張地圖。早晨去看一座寺，傍晚沿著河走，剩下的交給當天的心情。",
  note: "十月關西早晚微涼；大阪十月平年日高約 23.7°C、日低約 12.3°C，京都約 23.4°C／14.4°C，舒適步行鞋、輕薄外套與摺傘優先。",
  days: [
    { id: "day-1", short: "11", weekday: "日", label: "桃園 → 關西 → 京都", summary: "清晨出發，經關西機場前往京都。", stops: [
      { time: "04:40", leave: "05:00", title: "台灣桃園第一航廈", place: "桃園國際機場第一航廈", type: "arrival", transport: "報到／登機", duration: "20 分鐘", note: "航班起飛前完成報到與行李託運。", cost: 0 },
      { time: "06:40", leave: "10:25", title: "抵達關西機場", place: "大阪府泉佐野市泉州空港北 1", type: "arrival", transport: "國際航班", duration: "3 小時 45 分鐘", note: "入境、領行李、購買交通票券。", cost: 0, links: [{ label: "KIX 航班資訊", url: "https://www.kansai-airport.or.jp/en/flight/search?direction=ARR" }] },
      { time: "10:25", leave: "10:55", title: "入境・領行李・購買交通票券", place: "關西國際機場第一航廈", type: "train", transport: "機場內步行", duration: "30 分鐘", note: "確認利木津巴士乘車位置與票券。", cost: 0, links: [{ label: "KIX 官方旅客資訊", url: "https://www.kansai-airport.or.jp/en/" }] },
      { time: "10:56", leave: "11:18", title: "利木津巴士候車・出發", place: "關西國際機場利木津巴士站", type: "train", transport: "利木津巴士", duration: "22 分鐘", note: "前往關西機場巴士乘車處。", cost: 0, links: [{ label: "KATE 巴士時刻表", url: "https://www.kate.co.jp/en/timetable/" }] },
      { time: "11:18", leave: "12:30", title: "利木津巴士（關西機場 → 京都站）", place: "京都站八條口", type: "train", transport: "利木津巴士", duration: "1 小時 12 分鐘", note: "抵達京都站後前往飯店寄放行李。", cost: 3600, links: [{ label: "京都線官方時刻表", url: "https://www.keihanbus.jp/limousine/kix/limousine_kanku_kyoto.html" }] },
      { time: "12:35", leave: "12:40", title: "unito hotel residence Kyoto Station・寄放行李（第一晚）", place: "京都府京都市下京區東鹽小路町 9-2", type: "stay", transport: "步行", duration: "5 分鐘", note: "第一天住宿；只寄放行李後立即離開，不辦理正式入住。", cost: 0 },
      { time: "13:00", leave: "14:10", title: "本家 第一旭 本店 拉麵", place: "京都府京都市下京區東鹽小路町 845", type: "food", transport: "步行", duration: "1 小時 10 分鐘", note: "京都站旁的第一餐。若排隊較久，彈性調整。", cost: 1200 },
      { time: "14:30", leave: "15:30", title: "東寺（教王護國寺）", place: "京都府京都市南區九條町 1", type: "culture", transport: "步行", duration: "1 小時", note: "調整到下午較早時段；東寺有料區 17:00 關閉、16:30 最後入場。10/11 位於秋期特別公開期間，成人金堂・講堂票價以官方公告為準。", cost: 800, links: [{ label: "東寺官方開放時間與費用", url: "https://toji.or.jp/en/location/index.html" }] },
      { time: "15:55", leave: "17:20", title: "京都高島屋 S.C.", place: "京都府京都市下京區四條通河原町西入真町 52", type: "shopping", transport: "電車／步行", duration: "1 小時 25 分鐘", note: "從東寺前往四條河原町；逛街與採買。2026/8/1 起百貨營業時間為 10:30–20:00。", cost: 0, links: [{ label: "京都高島屋官方營業時間", url: "https://www.takashimaya.co.jp/kyoto/departmentstore/businesshours/" }] },
      { time: "17:25", leave: "18:00", title: "ESP KYOTO (@espkyoto)", place: "京都府京都市中京區中之町 543-1", type: "shopping", transport: "步行", duration: "35 分鐘", note: "與京都高島屋同在四條河原町一帶；官方營業時間 11:00–20:00。", cost: 0, links: [{ label: "ESP 官方店舖資訊", url: "https://www.espwebstore.com/ext/shop.html" }] }
    ]},
    { id: "day-2", short: "12", weekday: "一", label: "京都嵐山", summary: "搭上小火車，順著保津川慢慢下山。", stops: [
      { time: "06:30", leave: "07:00", title: "京都新阪急酒店（第二間飯店）", place: "京都府京都市下京區東鹽小路町 579", type: "stay", transport: "步行", duration: "30 分鐘", note: "第二天使用的不同飯店；與第一天的 unito hotel residence Kyoto Station 不同。早餐／出發準備。", cost: 0 },
      { time: "07:10", leave: "07:30", title: "JR 京都站", place: "京都府京都市下京區東鹽小路町", type: "train", transport: "步行／JR 嵯峨野線", duration: "20 分鐘", note: "建議搭 07:34 左右往龜岡方向的普通／快速列車，前往 JR 嵯峨嵐山站。", cost: 240, links: [{ label: "JR West 路線・時刻表", url: "https://www.westjr.co.jp/global/en/timetable/search_jp/" }] },
      { time: "07:34", leave: "07:59", title: "JR 嵯峨嵐山站（要轉搭小火車）", place: "京都府京都市右京區嵯峨天龍寺車道町 11-1", type: "train", transport: "JR 山陰本線", duration: "25 分鐘", note: "抵達後步行轉往嵯峨野觀光小火車嵯峨站；與上一站是同一段 JR 車程，票價只計一次。", cost: 0, links: [{ label: "JR West 路線・時刻表", url: "https://www.westjr.co.jp/global/en/timetable/search_jp/" }] },
      { time: "08:05", leave: "09:00", title: "嵯峨站轉乘／取票候車", place: "嵯峨野觀光鐵道 嵯峨站", type: "train", transport: "步行／取票／候車", duration: "55 分鐘", note: "從 JR 嵯峨嵐山站步行轉往嵯峨站；官方同日售票約 08:35 開始，預約客依票面時間報到。", cost: 0, links: [{ label: "官方票券說明", url: "https://www.sagano-kanko.co.jp/en/ticket/" }] },
      { time: "09:02", leave: "09:25", title: "嵯峨野觀光小火車（嵯峨 → 龜岡）", place: "嵯峨野觀光鐵道 嵯峨站", type: "train", transport: "嵯峨野觀光小火車", duration: "23 分鐘", note: "改用 2026 官方時刻表首班：嵯峨 09:02 出發、龜岡 09:25 抵達；原 08:30 時間早於官方首班。", cost: 880, links: [{ label: "官方時刻表／預約", url: "https://www.sagano-kanko.co.jp/en/index.php/" }] },
      { time: "09:35", leave: "09:45", title: "接駁至保津川遊船乘船處", place: "京都府龜岡市篠町山本地區", type: "nature", transport: "保津川遊船接駁巴士", duration: "10 分鐘", note: "依保津川官方小火車銜接例安排接駁；不再把龜岡站到乘船處誤寫成步行。", cost: 0, links: [{ label: "官方預約銜接說明", url: "https://www.hozugawakudari.jp/tickets/reservation" }] },
      { time: "09:45", leave: "09:55", title: "保津川遊船報到", place: "保津川遊船乘船場", type: "nature", transport: "步行／報到", duration: "10 分鐘", note: "10:00 預約時段前完成報到；10/12 是日本運動日國定假日，也是 10/10–10/12 三日連休最後一天，假日採隨時／人數到齊開船，實際出航仍以官方當日安排為準。", cost: 0, links: [{ label: "官方時刻表", url: "https://www.hozugawakudari.jp/service/timetable" }] },
      { time: "10:00", leave: "12:00", title: "保津川遊船（出發）", place: "保津川遊船乘船場", type: "nature", transport: "保津川遊船", duration: "2 小時", note: "修正原因：原 09:30 開船接不上官方 09:02 小火車；改為 09:02→09:25→09:35 接駁→10:00 預約時段，並保留假日隨時運航彈性。", cost: 6000, links: [{ label: "官方預約銜接說明", url: "https://www.hozugawakudari.jp/tickets/reservation" }, { label: "官方時刻表", url: "https://www.hozugawakudari.jp/service/timetable" }] },
      { time: "12:00", leave: "12:10", title: "抵達嵐山渡船口／渡月橋附近", place: "京都府京都市右京區嵯峨中之島町", type: "nature", transport: "步行", duration: "10 分鐘", note: "下船後前往午餐。", cost: 0 },
      { time: "12:15", leave: "12:55", title: "Wagyu Volcano Steak OAGARI（午餐）", place: "京都府京都市右京區嵯峨天龍寺芒之馬場町 3-25", type: "food", transport: "步行", duration: "40 分鐘", note: "午餐預約與候位依現場狀況。", cost: 4500 },
      { time: "13:05", leave: "13:30", title: "京都嵐山 和牛六重樓", place: "京都府京都市右京區嵯峨天龍寺芒之馬場町 3-25", type: "food", transport: "步行", duration: "25 分鐘", note: "與 Wagyu Volcano Steak OAGARI 為不同餐廳，兩間都要吃；此站安排快速用餐／品嚐。10:00 開門。", cost: 1500 },
      { time: "13:45", leave: "14:15", title: "天龍寺", place: "京都府京都市右京區嵯峨天龍寺芒之馬場町 68", type: "culture", transport: "步行", duration: "30 分鐘", note: "參觀庭園與法堂。", cost: 1000 },
      { time: "14:15", leave: "14:35", title: "竹林小徑", place: "京都府京都市右京區嵯峨天龍寺芒之馬場町", type: "nature", transport: "步行", duration: "20 分鐘", note: "避開人潮，沿主要步道散步。", cost: 0 },
      { time: "14:35", leave: "14:55", title: "野宮神社", place: "京都府京都市右京區嵯峨野宮町 1", type: "culture", transport: "步行", duration: "20 分鐘", note: "竹林小徑旁順路參拜。", cost: 0 },
      { time: "15:15", leave: "15:45", title: "祇王寺（推薦）或常寂光寺（二選一）", place: "京都府京都市右京區嵯峨鳥居本小坂町 32", type: "culture", transport: "步行", duration: "30 分鐘", note: "依體力與時間二選一；從野宮神社預留步行時間。", cost: 500 },
      { time: "15:45", leave: "16:15", title: "嵐山商店街", place: "京都府京都市右京區嵯峨天龍寺造路町", type: "shopping", transport: "步行", duration: "30 分鐘", note: "伴手禮與街邊小吃。", cost: 2000 },
      { time: "16:25", leave: "16:55", title: "渡月橋・桂川散步", place: "京都府京都市右京區嵯峨中之島町", type: "nature", transport: "步行", duration: "30 分鐘", note: "嵐山行程收尾。", cost: 0 },
      { time: "17:00", leave: "", title: "返回京都市區", place: "京都市區", type: "train", transport: "JR／阪急電車", duration: "彈性", note: "圖片未提供離開時間，依當日體力與晚餐安排調整。", cost: 500, links: [{ label: "JR West 時刻表", url: "https://www.westjr.co.jp/global/en/timetable/search_jp/" }, { label: "阪急電鐵官方", url: "https://www.hankyu.co.jp/global/en/" }] }
    ]},
    { id: "day-3", short: "13", weekday: "二", label: "清水寺・祇園・伏見稻荷", summary: "從清晨的清水坂，走到祇園的夜色。", stops: [
      { time: "06:30", leave: "06:50", title: "JR 京都站", place: "京都府京都市下京區東鹽小路町", type: "train", transport: "JR／公車", duration: "20 分鐘", note: "清晨出發前往清水寺。", cost: 300, links: [{ label: "京都市交通資訊", url: "https://www2.city.kyoto.lg.jp/koho/eng/access/transport.html" }] },
      { time: "07:01", leave: "07:25", title: "清水寺", place: "京都府京都市東山區清水 1-294", type: "culture", transport: "公車／步行", duration: "24 分鐘", note: "趁早參拜，避開上午人潮。", cost: 500, links: [{ label: "Google Maps 導航", url: "https://www.google.com/maps/search/?api=1&query=清水寺" }] },
      { time: "08:20", leave: "08:40", title: "二年坂、三年坂慢慢逛、咖啡、伴手禮", place: "京都府京都市東山區二年坂、三年坂", type: "shopping", transport: "步行", duration: "20 分鐘", note: "留時間拍照、喝咖啡與採買伴手禮。", cost: 2500 },
      { time: "10:50", leave: "11:00", title: "京都府京都市東山区桜屋町349-18", place: "京都府京都市東山区桜屋町349-18", type: "cafe", transport: "步行", duration: "10 分鐘", note: "圖片提供的地址，店名待補。", cost: 0, links: [{ label: "Google Maps 導航", url: "https://maps.app.goo.gl/1EhoR2rPJD8HhfBF9" }] },
      { time: "12:30", leave: "12:40", title: "PORTER STAND 京都", place: "京都府京都市下京區東鹽小路町", type: "shopping", transport: "步行／電車", duration: "10 分鐘", note: "京都站周邊採買。", cost: 0 },
      { time: "13:00", leave: "13:15", title: "祇園四条站", place: "京都府京都市東山區四條大橋東詰", type: "train", transport: "京阪本線", duration: "15 分鐘", note: "由京都站方向前往祇園。", cost: 300, links: [{ label: "京阪電車官方", url: "https://www.keihan.co.jp/traffic/station/" }] },
      { time: "14:00", leave: "15:00", title: "伏見稻荷大社（神樂鈴）", place: "京都府京都市伏見區深草藪之內町 68", type: "culture", transport: "JR／京阪電車", duration: "1 小時", note: "參拜與體驗神樂鈴。", cost: 500, links: [{ label: "JR West 路線・時刻表", url: "https://www.westjr.co.jp/global/en/timetable/search_jp/" }] },
      { time: "15:30", leave: "15:50", title: "回祇園", place: "京都府京都市東山區祇園", type: "train", transport: "京阪電車／步行", duration: "20 分鐘", note: "返回祇園一帶。", cost: 300, links: [{ label: "京阪電車官方", url: "https://www.keihan.co.jp/traffic/station/" }] },
      { time: "16:30", leave: "17:00", title: "八阪神社（神樂鈴）", place: "京都府京都市東山區祇園町北側 625", type: "culture", transport: "步行", duration: "30 分鐘", note: "參拜八阪神社與體驗神樂鈴。", cost: 0 },
      { time: "18:00", leave: "18:20", title: "祇園四条公車站／京阪本線", place: "祇園四条站", type: "train", transport: "公車／京阪本線", duration: "20 分鐘", note: "原表格離開時間 13:07 與抵達時間矛盾，先往後調整為 18:20。", cost: 300, links: [{ label: "京都市交通資訊", url: "https://www2.city.kyoto.lg.jp/koho/eng/access/transport.html" }, { label: "京阪電車官方", url: "https://www.keihan.co.jp/traffic/station/" }] }
    ]},
    { id: "day-4", short: "14", weekday: "三", label: "京都御苑・二條城・市區逛街", summary: "沿著烏丸線與京都老街，慢慢走到錦市場。", stops: [
      { time: "07:40", leave: "08:00", title: "京都車站（地下鐵烏丸線）", place: "京都府京都市下京區東鹽小路町", type: "train", transport: "京都地下鐵烏丸線", duration: "20 分鐘", note: "先從 JR／住宿方向走到烏丸線月台；08:05 左右再出發前往今出川，避免把進站與乘車時間重疊。", cost: 260, links: [{ label: "京都市地下鐵／公車", url: "https://www2.city.kyoto.lg.jp/koho/eng/access/transport.html" }, { label: "京都站烏丸線時刻表", url: "https://www2.city.kyoto.lg.jp/kotsu/tikadia/hyperdia/menu0221.htm" }] },
      { time: "08:05", leave: "08:15", title: "京都站 → 今出川站", place: "京都市營地下鐵烏丸線", type: "train", transport: "地下鐵烏丸線", duration: "10 分鐘", note: "改成明確的乘車段；原本 08:03 到站的寫法只有 3 分鐘銜接，無法表示實際乘車時間。", cost: 0, links: [{ label: "今出川站烏丸線時刻表", url: "https://www2.city.kyoto.lg.jp/kotsu/tikadia/hyperdia/menu0216.htm" }] },
      { time: "08:15", leave: "08:30", title: "今出川站 → 晴明神社", place: "京都府京都市上京區岡松町 → 晴明神社", type: "train", transport: "步行", duration: "15 分鐘", note: "補上今出川站出站後步行到晴明神社的時間。", cost: 0 },
      { time: "08:30", leave: "09:00", title: "晴明神社", place: "京都府京都市上京區晴明町 806", type: "culture", transport: "步行", duration: "30 分鐘", note: "參拜與拍攝五芒星社紋。", cost: 0 },
      { time: "09:15", leave: "10:00", title: "京都御苑", place: "京都府京都市上京區京都御苑", type: "nature", transport: "步行（轉移）", duration: "45 分鐘", note: "從晴明神社離開後預留約 15 分鐘步行，再在御苑內散步；不把 09:00 當成已抵達時間。", cost: 0 },
      { time: "10:20", leave: "11:10", title: "二條城", place: "京都府京都市中京區二條城町 541", type: "culture", transport: "步行／公車", duration: "50 分鐘", note: "從京都御苑前往二條城，預留約 20 分鐘轉移；參觀唐門與二之丸御殿。", cost: 1300 },
      { time: "11:30", leave: "12:35", title: "午餐（烏丸御池）", place: "京都府京都市中京區烏丸御池周邊", type: "food", transport: "步行／公車", duration: "1 小時 5 分鐘", note: "午餐店家待補；先保留用餐時段。", cost: 2500 },
      { time: "12:45", leave: "13:15", title: "APFR KYOTO", place: "京都府京都市中京區二條通御幸町東入山本町 439-1", type: "shopping", transport: "步行", duration: "30 分鐘", note: "香氛與生活用品；2026/10/14（週三）營業時間 11:00–19:00，週二定休。", cost: 0, links: [{ label: "APFR KYOTO 官方資訊", url: "https://www.apothekefragrance.jp/information/apfr-kyoto-%E3%82%AA%E3%83%BC%E3%83%97%E3%83%B3/" }] },
      { time: "13:35", leave: "13:55", title: "六角堂", place: "京都府京都市中京區堂之前町 248", type: "culture", transport: "步行", duration: "20 分鐘", note: "從 APFR KYOTO 預留約 20 分鐘步行，再順路參拜六角堂。", cost: 0 },
      { time: "14:00", leave: "15:00", title: "寺町通商店街", place: "京都府京都市中京區寺町通", type: "shopping", transport: "步行", duration: "1 小時", note: "逛京都市中心商店街。", cost: 0 },
      { time: "15:00", leave: "15:30", title: "新京極商店街", place: "京都府京都市中京區新京極通", type: "shopping", transport: "步行", duration: "30 分鐘", note: "與寺町通連續逛街。", cost: 0 },
      { time: "15:40", leave: "17:00", title: "錦市場", place: "京都府京都市中京區錦小路通", type: "food", transport: "步行", duration: "1 小時 20 分鐘", note: "小吃與市場採買；10/14（週三）市場不整體休市，但許多個別店家週三休息，出發前確認想去的店。", cost: 2200, links: [{ label: "錦市場官方營業說明", url: "https://www.kyoto-nishiki.or.jp/en/contact/" }] }
    ]},
    { id: "day-5", short: "15", weekday: "四", label: "京都去大阪", summary: "退房後前往勝尾寺，再搭北大阪急行與御堂筋線回難波，走進大阪市區。", stops: [
      { time: "07:40", leave: "08:00", title: "京都站／退房", place: "京都站", type: "stay", transport: "步行", duration: "20 分鐘", note: "退房、確認行李與交通票券；不要把 08:00 同時當成列車發車時間。大阪住宿地址仍待補，若無法先寄放行李，請安排宅配或車站置物櫃。", cost: 0 },
      { time: "08:10", leave: "08:40", title: "JR 新快速 → 大阪站", place: "京都站 → 大阪站", type: "train", transport: "JR 京都線・新快速", duration: "30 分鐘", note: "前往大阪站；抵達後不直接接下一段，先預留步行與站內轉乘時間。實際車次出發前再確認。", cost: 580, links: [{ label: "JR West 路線・時刻表", url: "https://www.westjr.co.jp/global/en/timetable/search_jp/" }] },
      { time: "08:40", leave: "08:55", title: "JR 大阪站 → 梅田站轉乘", place: "JR 大阪站 → Osaka Metro 梅田站", type: "train", transport: "步行／站內轉乘", duration: "15 分鐘", note: "補上 JR 大阪站到 Osaka Metro 梅田站的步行、找月台與進站時間。", cost: 0, links: [{ label: "Osaka Metro 梅田站資訊", url: "https://subway.osakametro.co.jp/en/station_guide/M/m16/joukouichi.php" }] },
      { time: "08:55", leave: "09:35", title: "梅田 → 箕面萱野", place: "Osaka Metro 梅田站 → 箕面萱野站", type: "train", transport: "Osaka Metro 御堂筋線・北大阪急行直通", duration: "約 40 分鐘", note: "改在完成轉乘後才搭往箕面萱野方向的直通列車；出發前查看梅田站往箕面萱野的時刻表。", cost: 480, links: [{ label: "梅田站往箕面萱野時刻表", url: "https://subway.osakametro.co.jp/en/station_guide/M/m16/joukouichi.php" }] },
      { time: "09:40", leave: "10:02", title: "箕面萱野 → 勝尾寺（直行巴士）", place: "箕面萱野站 → 勝尾寺", type: "train", transport: "阪急巴士 30 系統／直行", duration: "約 22 分鐘", note: "2026/10/15 為週四；抵達後預留 5 分鐘走到乘車處，官方平日 09:00 起約每 10 分鐘一班，09:40 為規劃班次，仍以當日班表為準。", cost: 800, links: [{ label: "勝尾寺直行巴士時刻表", url: "https://katsuo-ji-temple.or.jp/access/index.php" }] },
      { time: "10:10", leave: "11:20", title: "勝尾寺", place: "大阪府箕面市勝尾寺", type: "culture", transport: "步行", duration: "1 小時 10 分鐘", note: "參拜勝運達摩與庭園；平日開放至 17:00，最終受付 16:30。", cost: 500, links: [{ label: "Google Maps 導航", url: "https://www.google.com/maps/search/?api=1&query=勝尾寺" }, { label: "勝尾寺官方交通／巴士時刻表", url: "https://katsuo-ji-temple.or.jp/access/index.php" }] },
      { time: "11:30", leave: "11:52", title: "勝尾寺 → 箕面萱野", place: "勝尾寺 → 箕面萱野站", type: "train", transport: "阪急巴士 30 系統／直行", duration: "約 22 分鐘", note: "搭回箕面萱野再轉北大阪急行；回程班次依當日阪急巴士時刻表，若錯過 11:30 便順延。", cost: 800, links: [{ label: "勝尾寺回程巴士時刻表", url: "https://katsuo-ji-temple.or.jp/access/index.php" }] },
      { time: "12:00", leave: "12:40", title: "箕面萱野 → 難波", place: "箕面萱野站 → 難波站", type: "train", transport: "北大阪急行／Osaka Metro 御堂筋線直通", duration: "約 40 分鐘", note: "不再繞回千里中央；依班次直達難波。抵達後先處理行李，住宿或置物櫃位置待補。", cost: 530, links: [{ label: "Osaka Metro 難波站／時刻表", url: "https://subway.osakametro.co.jp/en/station_guide/M/m20/index.php" }] },
      { time: "12:55", leave: "13:25", title: "難波八阪神社", place: "大阪府大阪市浪速區元町 2-9-19", type: "culture", transport: "步行", duration: "30 分鐘", note: "從難波站步行前往；先參拜，再回難波用餐。", cost: 0 },
      { time: "13:25", leave: "13:45", route: "emma", title: "印 なんばパークス店 (Emma)", place: "大阪府大阪市浪速區難波中 2-10-70", type: "shopping", transport: "步行", duration: "20 分鐘", note: "Emma 的採買站點。", cost: 0 },
      { time: "13:45", leave: "14:30", title: "午餐（難波）", place: "大阪府大阪市中央區難波周邊", type: "food", transport: "步行", duration: "45 分鐘", note: "難波午餐店家待補。", cost: 2500 },
      { time: "14:45", leave: "16:10", title: "道頓堀", place: "大阪府大阪市中央區道頓堀", type: "nature", transport: "步行", duration: "1 小時 25 分鐘", note: "固力果跑跑人、戎橋與河畔散步。", cost: 0 },
      { time: "16:10", leave: "17:00", title: "心齋橋商店街", place: "大阪府大阪市中央區心齋橋筋", type: "shopping", transport: "步行", duration: "50 分鐘", note: "道頓堀與心齋橋相鄰，直接步行銜接；服飾、藥妝與伴手禮。大阪住宿地點仍待補。", cost: 5000 },
      { time: "17:00", leave: "17:45", route: "emma", title: "美國村站點 (Emma)", place: "大阪府大阪市中央區西心齋橋／LHPアメリカ村店／Blue in Green OSAKA", type: "shopping", transport: "步行", duration: "45 分鐘", note: "Emma 的美國村購物站點，涵蓋 LHPアメリカ村店和 Blue in Green OSAKA。", cost: 0 }
    ]},
    { id: "day-6", short: "16", weekday: "五", label: "任天堂世界", summary: "10/16（週五）主線為 SUPER NINTENDO WORLD；另提供 Overprint 購物分流，兩條路線可由不同同行者分開走。", stops: [
      { time: "07:00", leave: "07:45", title: "前往 Universal Studios Japan", place: "大阪府大阪市此花區櫻島 2-1-33", type: "train", transport: "JR 環狀線 → 夢咲線／Universal City", duration: "45 分鐘", note: "10/16 落在秋季活動期間，建議早到排隊；官方可能提早開始入場，實際營業時間與入場節奏前一天再確認。", cost: 400, links: [{ label: "USJ 官方營業時間", url: "https://www.usj.co.jp/web/en/us/park-guide/schedule/park-hour" }, { label: "JR West 路線・時刻表", url: "https://www.westjr.co.jp/global/en/timetable/search_jp/" }] },
      { time: "07:45", leave: "08:15", title: "園前集合／票券與官方 App 最後確認", place: "Universal Studios Japan 大門外", type: "fun", transport: "步行／排隊", duration: "30 分鐘", note: "所有同行者先到齊；Studio Pass QR code 離線保存，官方 App 已更新、登入，並預先登錄所有同行者票券。不要把註冊票券留到閘口前才做。", cost: 0, links: [{ label: "官方 App 說明", url: "https://www.usj.co.jp/web/en/us/enjoy/numbered-ticket/app/timed-entry-ticket" }, { label: "Studio Pass 官方說明", url: "https://www.usj.co.jp/web/en/us/tickets?lang=en" }] },
      { time: "08:15", leave: "08:35", title: "入園後立即取得任天堂世界入場資格", place: "Universal Studios Japan", type: "fun", transport: "官方 App／步行", duration: "20 分鐘", note: "若 Express Pass 或旅行社票券已含 Area Timed Entry Ticket: Advance Booking，依票面時段；否則入園後用 App 取得 Area Timed Entry／Standby Entry。票券可能提早發完，取得後時間與人數不能改。", cost: 0, links: [{ label: "SUPER NINTENDO WORLD 官方資訊", url: "https://www.usj.co.jp/web/en/us/areas/super-nintendo-world" }, { label: "官方整理券說明", url: "https://www.usj.co.jp/web/en/us/enjoy/numbered-ticket" }] },
      { time: "08:35", leave: "09:00", title: "SUPER NINTENDO WORLD 入場／定位", place: "SUPER NINTENDO WORLD™, Universal Studios Japan", type: "fun", transport: "園區內步行", duration: "25 分鐘", note: "穿過 Warp Pipe 後先確認同行者、洗手間、飲水點與第一站路線；拍照先控制在短時間，優先完成第一個指定設施。若入場時間延後，以下任天堂區塊整體順延。", cost: 0, links: [{ label: "SUPER NINTENDO WORLD 官方地圖／介紹", url: "https://www.usj.co.jp/web/en/us/areas/super-nintendo-world" }] },
      { time: "09:00", leave: "10:30", title: "Mario Kart: Koopa's Challenge", place: "SUPER NINTENDO WORLD™, Universal Studios Japan／Bowser's Castle", type: "fun", transport: "園區內步行／排隊", duration: "1.5 小時", note: "任天堂第一順位；先完成 Mario Kart，再依現場等待時間調整。官方身高基準為 122 cm 以上；107–122 cm 需由符合條件的同行者陪同。", cost: 0, links: [{ label: "Mario Kart 官方介紹", url: "https://www.usj.co.jp/web/en/us/attractions/mario-kart-koopas-challenge" }, { label: "身高限制官方說明", url: "https://www.usj.co.jp/web/en/us/service-guide/safe/height-restriction" }] },
      { time: "10:30", leave: "11:45", title: "Mine Cart Madness（Donkey Kong Country）", place: "SUPER NINTENDO WORLD™／Donkey Kong Country™", type: "fun", transport: "園區內步行／排隊", duration: "1 小時 15 分鐘", note: "任天堂第二順位；若等待過長就先改玩 Yoshi。設施有突然加速、落差、升降、霧氣／水氣等效果；官方身高基準為 122 cm 以上，107–122 cm 需陪同。", cost: 0, links: [{ label: "Mine Cart Madness 官方介紹", url: "https://www.usj.co.jp/web/en/us/attractions/donkey-kong-country-ride" }, { label: "Mine Cart Madness 安全規範", url: "https://www.usj.co.jp/web/en/us/service-guide/safe/donkey-kong-country-ride" }] },
      { time: "11:45", leave: "12:30", title: "Yoshi's Adventure／角色拍照", place: "SUPER NINTENDO WORLD™", type: "fun", transport: "園區內步行／排隊", duration: "45 分鐘", note: "完成 Yoshi 或依等待時間改拍角色、Super Star Plaza；Yoshi 適合全家，官方身高基準為 122 cm 以上，92–122 cm 需陪同。", cost: 0, links: [{ label: "Yoshi's Adventure 官方介紹", url: "https://www.usj.co.jp/web/en/us/attractions/yoshis-adventure" }] },
      { time: "12:30", leave: "13:30", title: "Kinopio's Café 午餐／Priority Seating", place: "SUPER NINTENDO WORLD™／Kinopio's Café™", type: "food", transport: "園區內步行／Mobile Ordering", duration: "1 小時", note: "午餐以 Kinopio's Café 為第一選擇；官方寫明可於當日餐廳入口確認 Priority Seating，且 Mobile Ordering 只可在任天堂世界內使用。若額滿，改 Yoshi's Snack Island 或其他園區餐點，不為吃飯離開任天堂區。", cost: 2800, links: [{ label: "Kinopio's Café 官方資訊", url: "https://www.usj.co.jp/web/en/us/restaurants/kinopios-cafe" }, { label: "Mobile Order 官方餐廳列表", url: "https://www.usj.co.jp/web/en/us/restaurants/mobile-order/restaurants-accepting-mobile-orders" }] },
      { time: "13:30", leave: "14:45", title: "Power-Up Band Key Challenges（可選）", place: "SUPER NINTENDO WORLD™", type: "fun", transport: "園區內步行／互動任務", duration: "1 小時 15 分鐘", note: "想玩互動任務才購買 Power-Up Band；它不是進入任天堂世界的必要條件，但 Key Challenges 需要 Band，集滿 3 把鑰匙才可挑戰 Bowser Jr. Final Battle。不買就把時間改成休息、拍照或重玩設施。Band 不需充電，但不是防水。", cost: 4500, links: [{ label: "Power-Up Band 官方介紹", url: "https://www.usj.co.jp/web/en/us/attractions/power-up-band-key-challenges" }, { label: "SUPER NINTENDO WORLD App／Band 說明", url: "https://www.usj.co.jp/web/en/us/areas/super-nintendo-world/app" }] },
      { time: "14:45", leave: "15:45", title: "1-UP Factory／Funky's Fly 'n' Buy／任天堂商店", place: "SUPER NINTENDO WORLD™", type: "shopping", transport: "園區內步行", duration: "1 小時", note: "集中處理伴手禮、角色拍照與 Donkey Kong 商品；先確認想買的品項，再把購物袋整理好，避免反覆回店。5 週年商品與餐點可能限量，設計、價格、販售方式與庫存以現場為準。", cost: 0, links: [{ label: "SUPER NINTENDO WORLD 官方商店／活動", url: "https://www.usj.co.jp/web/en/us/areas/super-nintendo-world" }] },
      { time: "15:45", leave: "17:30", title: "任天堂世界補拍・重玩・Meet-Up", place: "SUPER NINTENDO WORLD™", type: "fun", transport: "園區內步行", duration: "1 小時 45 分鐘", note: "回頭完成早上沒玩到的項目；依 App 即時等待時間、臨時休止與當日活動調整。2026 年為任天堂世界 5 週年，Meet-Up／特別活動時間要以官方當日表為準。", cost: 0, links: [{ label: "5 週年官方活動資訊", url: "https://www.usj.co.jp/web/en/us/areas/super-nintendo-world" }, { label: "USJ 官方 App", url: "https://www.usj.co.jp/web/en/us/enjoy/app?hideToolbar=false" }] },
      { time: "17:30", leave: "18:30", title: "任天堂世界最後巡回／晚餐／最後採買", place: "SUPER NINTENDO WORLD™", type: "fun", transport: "園區內步行", duration: "1 小時", note: "把最後一輪拍照、飲水、廁所與伴手禮一次完成；不為追其他園區而放棄任天堂主線。若當日營業或設施時間提早結束，提前移到備案。", cost: 1800, links: [{ label: "SUPER NINTENDO WORLD 餐飲官方資訊", url: "https://www.usj.co.jp/web/en/us/restaurants/super-nintendo-world-food" }] },
      { time: "18:30", leave: "19:30", title: "離開任天堂世界／其他區域備選", place: "Universal Studios Japan", type: "fun", transport: "園區內步行", duration: "1 小時", note: "只有在 Mario Kart、Mine Cart、Yoshi 與任天堂購物都完成後才離開主區；10/16 在 Halloween Horror Nights 活動期間，若不參加恐怖項目就依安全路線走，別為了追活動硬撐。", cost: 0, links: [{ label: "USJ 秋季活動官方資訊", url: "https://www.usj.co.jp/web/en/us/events/halloween-extreme-autumn-2026" }, { label: "USJ 官方最新公告", url: "https://www.usj.co.jp/web/en/us/park-guide/schedule/" }] },
      { time: "19:30", leave: "20:30", title: "離園／返回住宿地", place: "Universal City Station／CityWalk", type: "train", transport: "步行／JR 夢咲線 → JR 環狀線", duration: "1 小時", note: "普通 Studio Pass 離園後不可再入園；要在出園前完成廁所、飲水、取物與最後採買。若留到 Halloween 夜間活動，回程時間另以當日官方安排為準。", cost: 400, links: [{ label: "JR West 路線・時刻表", url: "https://www.westjr.co.jp/global/en/timetable/search_jp/" }, { label: "Studio Pass 官方說明", url: "https://www.usj.co.jp/web/en/us/tickets?lang=en" }] },
      { time: "09:00", leave: "09:10", route: "overprint", title: "待確大阪飯店 → JR難波駅", place: "大阪市區住宿地 → JR難波駅", type: "train", transport: "步行", duration: "5–10 分鐘", note: "依實際飯店位置調整；JR難波駅是這條路線唯一的 JR 起點站，與地鐵／近鐵的難波駅不同。", cost: 900 },
      { time: "09:10", leave: "09:20", route: "overprint", title: "JR難波駅 → 天王寺駅", place: "JR難波駅 → JR天王寺駅", type: "train", transport: "JR大和路線", duration: "約 5 分鐘", note: "月台上往奈良或加茂方向的列車都會停天王寺，不用特別挑車次，也不用換月台。", cost: 0 },
      { time: "09:20", leave: "09:45", route: "overprint", title: "天王寺駅 → 大阪駅", place: "JR天王寺駅 → JR大阪駅", type: "train", transport: "JR大阪環状線／往大阪方向", duration: "約 20 分鐘", note: "天王寺站內跟著 JR乗り換え／大阪環状線指標走；班次密集，預留轉移與等車時間。", cost: 0 },
      { time: "09:45", leave: "09:55", route: "overprint", title: "大阪駅 → 尼崎駅", place: "JR大阪駅 → JR尼崎駅", type: "train", transport: "JR神戸線／快速・新快速", duration: "約 10 分鐘", note: "搭往三ノ宮或姫路方向的快速／新快速；新快速較快。", cost: 0 },
      { time: "09:55", leave: "10:00", route: "overprint", title: "尼崎駅 → あまがさき Q's MALL", place: "JR尼崎駅 → あまがさきキューズモール", type: "shopping", transport: "步行", duration: "3–5 分鐘", note: "出站後跟著商場指標走，站內連通，通常不需要再找其他交通工具。", cost: 0 },
      { time: "10:00", leave: "10:45", route: "overprint", title: "Blue in Green 尼崎店（overprint 店鋪）", place: "兵庫県尼崎市潮江1丁目3-1 あまがさきキューズモール2F", type: "shopping", transport: "商場內步行", duration: "45 分鐘", note: "overprint 店鋪，確定營業。", cost: 0 },
      { time: "10:45", leave: "11:30", route: "overprint", title: "午餐（Q's MALL 內）", place: "あまがさきキューズモール餐廳／美食街", type: "food", transport: "商場內步行", duration: "45 分鐘", note: "直接在 Q's MALL 內用餐，非 overprint 店鋪，不需要另外移動。", cost: 0 },
      { time: "11:30", leave: "11:50", route: "overprint", title: "尼崎駅 → 海老江駅", place: "JR尼崎駅 → JR海老江駅", type: "train", transport: "JR東西線／直通", duration: "約 15 分鐘", note: "JR神戸線與 JR東西線在尼崎直通運轉；若搭到往京橋／学研都市線方向的列車，可同車繼續坐，不用下車換月台。", cost: 0 },
      { time: "11:50", leave: "12:00", route: "overprint", title: "海老江駅 → over print OSAKA", place: "JR海老江駅 → 大阪府大阪市福島区海老江7-22-24", type: "shopping", transport: "步行", duration: "5–8 分鐘", note: "從海老江站出站後步行前往直營店。", cost: 0 },
      { time: "12:00", leave: "13:00", route: "overprint", title: "over print OSAKA 直營店（overprint 店鋪）", place: "大阪府大阪市福島区海老江7-22-24", type: "shopping", transport: "店內巡店", duration: "1 小時", note: "營業日待確認；官網日曆目前只排到 8 月，9、10 月尚未公布。若當日未營業，直接保留為梅田／難波自由時間。", cost: 0 },
      { time: "13:00", leave: "13:10", route: "overprint", title: "海老江駅 → 大阪駅／北新地", place: "JR海老江駅 → 大阪駅／北新地", type: "train", transport: "JR東西線", duration: "約 10 分鐘", note: "由海老江原路返回大阪站／北新地一帶，再轉 JR大阪環状線。", cost: 0 },
      { time: "13:10", leave: "13:35", route: "overprint", title: "大阪駅 → 天王寺駅", place: "JR大阪駅 → JR天王寺駅", type: "train", transport: "JR大阪環状線", duration: "約 20 分鐘", note: "搭往天王寺方向的環狀線班次。", cost: 0 },
      { time: "13:35", leave: "13:45", route: "overprint", title: "天王寺駅 → JR難波駅", place: "JR天王寺駅 → JR難波駅", type: "train", transport: "JR大和路線", duration: "約 5 分鐘", note: "回到 JR難波駅後步行返回飯店。", cost: 0 },
      { time: "13:45", leave: "13:55", route: "overprint", title: "JR難波駅 → 飯店", place: "JR難波駅 → 大阪市區住宿地", type: "stay", transport: "步行", duration: "5–10 分鐘", note: "依實際飯店位置調整。", cost: 0 },
      { time: "13:55", leave: "", route: "overprint", title: "自由時間（非 overprint 店鋪）", place: "大阪市區／梅田或難波周邊", type: "nature", transport: "步行／大阪 Metro", duration: "彈性", note: "13:45 回飯店後開始；可視 over print OSAKA 是否營業與當天體力，加開梅田或難波周邊的悠閒時間。", cost: 0 }
    ], routeNotes: [{
      route: "overprint",
      title: "Overprint 分流｜詳細說明",
      intro: "這條路線與任天堂世界主線互斥，適合其他同行者平行安排；只安排 2 間 overprint 店鋪，13:45 回飯店後的時間保持彈性。",
      sections: [
        { title: "一、飯店 → JR難波駅", text: "步行約 5–10 分鐘（依實際飯店位置調整）。JR難波駅是本次行程唯一的 JR 起點站，跟地鐵／近鐵的「難波駅」是不同站體，出發前先用地圖確認清楚別走錯。" },
        { title: "二、JR難波駅 → 天王寺駅（JR大和路線）", text: "月台上車廂會顯示往「奈良」或「加茂」方向，兩者都會停天王寺，不用特別挑車次。車程約 5 分鐘，不用換月台。" },
        { title: "三、天王寺駅 → 大阪駅（JR大阪環状線）", text: "天王寺是大站，下車後跟著「JR乗り換え」或「大阪環状線」指標走。搭往「大阪」方向的班次，車程約 20 分鐘，班次密集，約 3–5 分鐘一班。" },
        { title: "四、大阪駅 → 尼崎駅（JR神戸線）", text: "在大阪駅轉乘往「三ノ宮」「姫路」方向的列車，搭「快速」或「新快速」都可以（新快速較快）。車程約 10 分鐘。" },
        { title: "五、尼崎駅 → あまがさき Q's MALL", text: "出站後跟著商場指標走，約 3–5 分鐘，站內連通不太會迷路。Blue in Green 尼崎店地址：兵庫県尼崎市潮江1丁目3-1 あまがさきキューズモール2F；午餐直接在 Q's MALL 內解決，非 overprint 店鋪，不用再移動。" },
        { title: "六、尼崎駅 → 海老江駅（JR東西線）", text: "這段最輕鬆，JR神戸線跟 JR東西線在尼崎是直通運轉，同一班車繼續坐即可，不用下車換月台；車廂會顯示「京橋」或「学研都市線」方向，車程約 15 分鐘。" },
        { title: "七、海老江駅 → over print OSAKA", text: "出站步行約 5–8 分鐘。over print OSAKA 直營店地址：大阪府大阪市福島区海老江7-22-24；營業日待確認，官網日曆目前只排到 8 月，9、10 月尚未公布。" },
        { title: "八、返程", text: "海老江 →（JR東西線）→ 大阪駅／北新地 →（轉 JR大阪環状線）→ 天王寺駅 →（轉 JR大和路線）→ JR難波駅，全程約 30–35 分鐘，2 次轉乘。" }
      ],
      tipsTitle: "新手小提醒",
      tips: [
        "用 IC 卡，不用每站買票。ICOCA、Suica、PASMO 全國通用，進站感應、出站感應即可；中途在天王寺、大阪轉乘都不用出閘門補票，系統會自動算好全程車資。建議在關西機場或任一 JR 站先買一張 ICOCA（可加值）。",
        "月台找不到路時，直接找站務員或看電子看板。天王寺、大阪都有英文／中文標示，也可以打開 Google Maps 或 Yahoo!乗換案内 App，輸入起訖站確認月台、發車時間與是否換車。",
        "車資抓大概 700–900 円／人（單趟去回），實際金額以 IC 卡感應後的顯示為準，不用先精算。午餐費用另計。",
        "這天只安排 2 間 overprint 店鋪；下午 13:45 後是空白時段。over print OSAKA 若確認沒開，行程會更空，可以視現場狀況加開一段梅田或難波周邊的悠閒時間。"
      ]
    }]},
    { id: "day-7", short: "17", weekday: "六", label: "大阪在地生活＋購物", summary: "從市場早餐開始，走過天神橋與北濱，最後逛梅田。", stops: [
      { time: "07:40", leave: "", title: "飯店出發", place: "大阪市區住宿地", type: "train", transport: "大阪 Metro／步行", duration: "彈性", note: "圖片只有抵達時間欄；實際出發時間以住宿地點與交通狀況調整。", cost: 300, links: [{ label: "Osaka Metro 官方", url: "https://subway.osakametro.co.jp/en/" }] },
      { time: "08:00", leave: "", title: "木津市場", place: "大阪府大阪市浪速區敷津東 2-2-8", type: "food", transport: "大阪 Metro／步行", duration: "彈性", note: "市場早餐與在地食材；10/17（週六）官方營業時間 05:30–18:00，各店開店時間不同。", cost: 1800, links: [{ label: "木津市場官方資訊", url: "https://kizu-ichiba.com/introduction/" }, { label: "Google Maps 導航", url: "https://www.google.com/maps/search/?api=1&query=大阪木津市場" }] },
      { time: "09:30", leave: "", title: "木津市場 → 扇町站（大阪 Metro）", place: "扇町站（大阪 Metro）", type: "train", transport: "大阪 Metro", duration: "彈性", note: "由木津市場前往扇町；實際搭乘路線以當日 App 查詢為準。", cost: 240, links: [{ label: "Osaka Metro 官方", url: "https://subway.osakametro.co.jp/en/" }] },
      { time: "10:00", leave: "", title: "SAKImotobakery and more 扇町店", place: "大阪府大阪市北區天神橋 3-7-13 プラーヴォ扇町 1F", type: "cafe", transport: "步行", duration: "彈性", note: "嵜本ベーカリー and more 扇町店；官方營業時間 08:00–19:00，麵包、早餐與咖啡。", cost: 1200, links: [{ label: "嵜本官方店舖資訊", url: "https://yoyaku-sakimoto.com/" }, { label: "Google Maps 導航", url: "https://www.google.com/maps/search/?api=1&query=SAKImotobakery%20and%20more%20扇町店" }] },
      { time: "11:00", leave: "", title: "天神橋筋商店街", place: "大阪府大阪市北區天神橋筋商店街", type: "shopping", transport: "步行", duration: "彈性", note: "日本最長商店街之一；適合邊走邊吃、慢慢逛。", cost: 2500 },
      { time: "12:30", leave: "", title: "午餐", place: "大阪府大阪市北區天神橋周邊", type: "food", transport: "步行", duration: "彈性", note: "午餐店家待補；保留在天神橋筋附近用餐。", cost: 2500 },
      { time: "13:35", leave: "", title: "大阪天滿宮", place: "大阪府大阪市北區天神橋 2-1-8", type: "culture", transport: "步行", duration: "彈性", note: "參拜與散步。", cost: 0 },
      { time: "14:20", leave: "", title: "中之島公園／北濱咖啡街", place: "大阪府大阪市北區中之島 1 丁目", type: "cafe", transport: "大阪 Metro／步行", duration: "彈性", note: "咖啡、河畔散步；依體力安排停留。", cost: 1200, links: [{ label: "大阪觀光官方", url: "https://osaka-info.jp/en/" }] },
      { time: "15:20", leave: "", title: "前往梅田", place: "大阪梅田站", type: "train", transport: "大阪 Metro／步行", duration: "彈性", note: "由北濱方向前往梅田購物區。", cost: 240, links: [{ label: "Osaka Metro 官方", url: "https://subway.osakametro.co.jp/en/" }] },
      { time: "15:35", leave: "16:00", title: "Grand Front Osaka", place: "大阪府大阪市北區大深町 4-1", type: "shopping", transport: "步行", duration: "25 分鐘", note: "梅田第一站購物。", cost: 0 },
      { time: "16:00", leave: "16:20", route: "emma", title: "印 NU茶屋町＋店 (Emma)", place: "大阪府大阪市北區茶屋町 10-12", type: "shopping", transport: "步行", duration: "20 分鐘", note: "Emma 的採買站點。", cost: 0 },
      { time: "16:25", leave: "", title: "LUCUA Osaka", place: "大阪府大阪市北區梅田 3-1-3", type: "shopping", transport: "步行", duration: "彈性", note: "服飾、生活雜貨與伴手禮；LHP LUCUA 大阪就在同一棟樓 7F。", cost: 0 },
      { time: "17:15", leave: "", title: "Yodobashi Umeda", place: "大阪府大阪市北區大深町 1-1", type: "shopping", transport: "步行", duration: "彈性", note: "電器、藥妝與最後採買。", cost: 0 },
      { time: "18:20", leave: "", title: "晚餐（梅田）", place: "大阪府大阪市北區梅田周邊", type: "food", transport: "步行", duration: "彈性", note: "梅田晚餐店家待補。", cost: 3500 }
    ]},
    { id: "day-8", short: "18", weekday: "日", label: "回祖國", summary: "最後採買、臨空城，再搭晚班機回家。", stops: [
      { time: "08:00", leave: "09:00", title: "早餐／Check out", place: "大阪市區住宿地", type: "stay", transport: "步行", duration: "1 小時", note: "退房、確認行李與護照。", cost: 0 },
      { time: "09:10", leave: "10:20", title: "難波咖啡廳（Brooklyn Roasting × Lilo Coffee × Arabica 等）", place: "大阪府大阪市中央區難波周邊", type: "cafe", transport: "步行", duration: "1 小時 10 分鐘", note: "最後一杯咖啡與早餐。", cost: 1800 },
      { time: "10:30", leave: "12:00", title: "美國村（古著、潮流服飾、咖啡）", place: "大阪府大阪市中央區西心齋橋 2 丁目", type: "shopping", transport: "大阪 Metro／步行", duration: "1.5 小時", note: "最後採買；注意行李容量。", cost: 5000, links: [{ label: "Osaka Metro 官方", url: "https://subway.osakametro.co.jp/en/" }] },
      { time: "12:00", leave: "13:00", title: "午餐", place: "大阪市區／心齋橋周邊", type: "food", transport: "步行", duration: "1 小時", note: "午餐店家待補。", cost: 2500 },
      { time: "13:00", leave: "13:55", title: "難波／南海難波站 → 臨空城站", place: "大阪市區 → 南海臨空城站", type: "train", transport: "步行／南海電鐵機場線・機場急行", duration: "約 55 分鐘", note: "補上午餐後由大阪市區前往臨空城的交通段；先走到南海難波站，再依官方時刻表搭乘普通／機場急行。若搭 Rapi:t，需另付特急費。普通票費用先以約 ¥820 估算。", cost: 820, links: [{ label: "南海電鐵時刻表", url: "https://www.nankai.co.jp/en_railway/access-timetable" }, { label: "南海難波站資訊", url: "https://www.nankai.co.jp/en_railway/traffic/station/namba.html" }] },
      { time: "14:00", leave: "15:30", title: "臨空城 Premium Outlets", place: "大阪府泉佐野市りんくう往来南 3-28", type: "shopping", transport: "步行", duration: "1.5 小時", note: "從臨空城站步行約 5 分鐘到 Outlet；先在臨空城購物，再前往機場。", cost: 0, links: [{ label: "Rinku Premium Outlets 官方", url: "https://www.premiumoutlets.co.jp/chs/rinku/" }, { label: "臨空城站資訊／時刻表", url: "https://www.nankai.co.jp/en_railway/traffic/station/rinkutown.html" }] },
      { time: "15:40", leave: "16:00", title: "臨空城 → 關西機場", place: "關西國際機場", type: "train", transport: "南海電鐵／機場線", duration: "20 分鐘", note: "從臨空城站前往機場；實際乘車約數分鐘，時段包含等車與站內移動，普通票先以官方特定票價 ¥370 計。", cost: 370, links: [{ label: "南海電鐵時刻表", url: "https://www.nankai.co.jp/en_railway/access-timetable" }, { label: "臨空城站資訊／時刻表", url: "https://www.nankai.co.jp/en_railway/traffic/station/rinkutown.html" }] },
      { time: "16:00", leave: "20:55", title: "關西機場（退稅、托運、免稅店、晚餐）", place: "大阪府泉佐野市泉州空港北 1", type: "arrival", transport: "機場內步行", duration: "4 小時 55 分鐘", note: "辦理退稅、托運、安檢與免稅店；晚餐留在機場解決。", cost: 2500, links: [{ label: "關西機場官方", url: "https://www.kansai-airport.or.jp/en/" }] },
      { time: "20:55", leave: "23:05", title: "其他旅客｜亞洲航空", place: "關西機場 → 桃園機場", type: "arrival", transport: "亞洲航空", duration: "2 小時 10 分鐘", note: "其他旅客（包含和學）搭乘的回程航班，與 Emma 的航班不同。航班編號待補。", cost: 0 },
      { time: "13:25", leave: "15:20", route: "emma", title: "Emma｜星宇航空", place: "關西機場 → 桃園機場", type: "arrival", transport: "星宇航空", duration: "1 小時 55 分鐘", note: "Emma 搭乘的回程航班，與其他旅客為不同班機。航班編號待補。", cost: 0 }
    ]}
  ],
  budget: [
    { label: "交通", key: "transport", amount: 12640, icon: "↝", tone: "blue" },
    { label: "餐費", key: "food", amount: 34200, icon: "⌁", tone: "orange" },
    { label: "門票／購物／彈性", key: "shopping", amount: 32600, icon: "✳", tone: "green" }
  ],
  reminders: [
    { title: "入境前｜Visit Japan Web", text: "先完成入境與海關資料，將 QR code 截圖並保存在離線相簿；護照姓名、航班與住宿資料要完全一致。", links: [{ label: "官方入境服務", url: "https://www.digital.go.jp/en/policies/visit_japan_web" }] },
    { title: "交通日｜先看官方時刻表", text: "JR、京都地下鐵、Osaka Metro、南海電鐵與勝尾寺直行巴士都要在出發前再查一次；行程表的時間是規劃值，不代表已完成訂位。", links: [{ label: "JR West 時刻表", url: "https://www.westjr.co.jp/global/en/timetable/search_jp/" }, { label: "京都市營地下鐵時刻表", url: "https://www2.city.kyoto.lg.jp/kotsu/tikadia/tikatime.htm?iframe=true" }, { label: "Osaka Metro 梅田站時刻表", url: "https://subway.osakametro.co.jp/en/station_guide/M/m16/joukouichi.php" }, { label: "南海電鐵時刻表", url: "https://www.nankai.co.jp/en_railway/access-timetable" }, { label: "勝尾寺直行巴士時刻表", url: "https://katsuo-ji-temple.or.jp/access/index.php" }] },
    { title: "京都｜尊重街區與寺社", text: "祇園不要進入私人道路或住宅區；不擋路、不追拍、不邊走邊吃，垃圾帶走。", links: [{ label: "京都官方禮儀", url: "https://kyoto.travel/en/responsible-travel/mind-your-manners/" }] },
    { title: "USJ 前一晚", text: "更新官方 App、先把所有同行者 Studio Pass 登錄進去、把票券 QR code／Express Pass 時段／住宿地址離線保存，並確認 10/16 官方營業時間、設施休止與當日活動表。", links: [{ label: "USJ 官方 App／整理券", url: "https://www.usj.co.jp/web/en/us/enjoy/numbered-ticket/app/timed-entry-ticket" }, { label: "USJ 營業時間", url: "https://www.usj.co.jp/web/en/us/park-guide/schedule/park-hour" }, { label: "Studio Pass 官方說明", url: "https://www.usj.co.jp/web/en/us/tickets?lang=en" }] },
    { title: "10/16｜任天堂世界主線", text: "入園後第一件事是取得 SUPER NINTENDO WORLD 的 Area Timed Entry／Standby Entry；若票券已含 Advance Booking 就依票面時段。入場資格不保證每項設施、餐廳或商店都能使用，當天休止與人潮要以 App／官方公告為準。", links: [{ label: "SUPER NINTENDO WORLD 官方資訊", url: "https://www.usj.co.jp/web/en/us/areas/super-nintendo-world" }, { label: "官方整理券規則", url: "https://www.usj.co.jp/web/en/us/enjoy/numbered-ticket" }] },
    { title: "10/16｜秋季 Halloween 活動", text: "10/16 位於 2026/9/11–11/8 的 Halloween Horror Nights 期間；若不參加恐怖項目，完成任天堂主線後可提早離園。園內不要奔跑或驚嚇殭屍／工作人員，穿運動鞋，並留意街頭活動與人流；5 歲以下不建議、12 歲以下體驗需家長同意。", links: [{ label: "Halloween Horror Nights 官方", url: "https://www.usj.co.jp/web/en/us/events/halloween-extreme-autumn-2026/halloween-horror-nights" }, { label: "秋季活動注意事項", url: "https://www.usj.co.jp/web/en/us/news/2026/0709" }] },
    { title: "嵐山日｜觀光列車與遊船", text: "10/12 已按官方銜接修正為 09:02 小火車→09:25 龜岡→09:35 接駁→10:00 預約時段；原因是原 08:30 小火車早於官方首班，且假日遊船採隨時運航。出發前仍要確認車次、預約與運航狀況。", links: [{ label: "嵯峨野觀光鐵道", url: "https://www.sagano-kanko.co.jp/en/index.php/" }, { label: "保津川遊船預約銜接", url: "https://www.hozugawakudari.jp/tickets/reservation" }, { label: "保津川遊船時刻表", url: "https://www.hozugawakudari.jp/service/timetable" }] },
    { title: "10/12｜日本運動日（國定假日）", text: "2026/10/12（週一）為日本國定假日「運動日」，也是 10/10–10/12 週末加假日三日連休的最後一天。京都與嵐山人潮、交通及保津川遊船都要按假日狀況預留，熱門景點、列車、遊船與餐廳提前確認／預約。", links: [{ label: "日本內閣府國定假日", url: "https://www8.cao.go.jp/chosei/shukujitsu/gaiyou.html" }] },
    { title: "2026/10｜日本行事曆與人潮", text: "10/11（日）抵達京都、10/12（一）嵐山、10/17（六）與 10/18（日）都落在週末／假日人潮範圍；USJ 10/16（五）雖是平日，仍在秋季 Halloween 活動期間。熱門交通、景點、餐廳與票券請保留替代時段。", links: [{ label: "京都市官方活動日曆", url: "https://www.city.kyoto.lg.jp/main/event1/calendar_list.html" }, { label: "大阪市官方活動日曆", url: "https://www.city.osaka.lg.jp/main/event2/next2.html" }] },
    { title: "2026/10｜天氣目前只能看趨勢", text: "截至 2026/8/21，10/11–10/18 尚未進入可靠逐日預報窗口。日本氣象廳目前近畿 8–10 月展望為氣溫平年並或偏高、降水量大致平年；1991–2020 平年值為大阪 10 月平均 19.5°C／日高 23.7°C／日低 12.3°C，京都平均 18.4°C／日高 23.4°C／日低 14.4°C。每天戶外站點仍以出發前 7–10 天與前一晚公告為準。", links: [{ label: "JMA 近畿季節展望", url: "https://www.data.jma.go.jp/cpd/longfcst/kaisetsu/?region=010600&term=P3M" }, { label: "JMA 大阪平年值", url: "https://www.data.jma.go.jp/stats/data/en/normal/normal.html" }, { label: "JMA 京都平年值", url: "https://www.data.jma.go.jp/stats/etrn/view/nml_sfc_ym.php?block_no=47759&prec_no=61" }] },
    { title: "出發前 7–10 天｜逐日天氣", text: "10/11–10/18 的逐日降雨、颱風、氣溫與強風要在接近出發時重查；尤其 10/12 保津川遊船、10/15 勝尾寺、10/16 USJ、10/18 臨空城都是戶外／轉乘密集日。雨天優先保留室內購物，遊船、交通與 USJ 依官方運行／休止資訊調整。", links: [{ label: "JMA 大阪 7 日預報", url: "https://www.jma.go.jp/bosai/forecast/#area_type=offices&area_code=270000" }, { label: "JMA 京都 7 日預報", url: "https://www.jma.go.jp/bosai/forecast/#area_type=offices&area_code=260000" }, { label: "JMA 大阪警報", url: "https://www.jma.go.jp/bosai/warning/#area_type=offices&area_code=270000" }] },
    { title: "10/17｜大阪舞洲相撲秋巡業（可選分流）", text: "官方公告為 2026/10/17（六）09:00 開場、約 14:30 結束，地點在大阪舞洲的 Ookini Arena Maishima。若有人想看相撲，請當作與 Day 7 梅田路線互斥的獨立行程；不要直接塞進木津市場到梅田的既有時段，票券與舞洲交通另確認。", links: [{ label: "日本相撲協會秋巡業日程", url: "https://www.sumo.or.jp/EnJungyo/schedule" }, { label: "大阪舞洲場所官方", url: "https://osaka-maishima.sumo-jungyo.jp/" }] },
    { title: "VIVOBAREFOOT KYOTO｜週三店休", text: "2026/10/14（週三）京都店固定週二、週三休店，已從當日行程移除；若要購買，改排週一、週四至週六 12:00–19:00，或週日 12:00–18:00。", links: [{ label: "VIVOBAREFOOT Kyoto 官方資訊", url: "https://vivobarefoot.co.jp/blogs/partner-shop/vivobarefoot-kyoto" }] },
    { title: "花費口徑", text: "花費頁為目前各行程站點的預估合計，包含交通、餐食、門票與購物／彈性項目；不含機票、住宿與尚未填入的個人消費。" },
    { title: "住宿與行李", text: "第一天 unito 是寄放行李後離開，不是正式入住；第二天是不同的京都新阪急酒店。10/15 晚上改住大阪，住宿地址仍要補入。" },
    { title: "交通轉乘", text: "車站月台、出口與巴士站可能需要步行時間；預留至少 10–15 分鐘轉乘，看到『建議搭乘』不代表已完成訂位。" },
    { title: "餐廳與排隊", text: "第一旭、嵐山兩間和牛餐廳、USJ 餐廳與熱門咖啡店都可能排隊；預約、候位與替代店家要事先想好。" },
    { title: "寺社與街區禮儀", text: "寺社內保持安靜、依規定參拜；祇園與住宅街不要進入私人道路、不追拍工作人員或居民，拍照先看現場標示。", links: [{ label: "京都官方禮儀", url: "https://kyoto.travel/en/responsible-travel/mind-your-manners/" }] },
    { title: "購物與退稅", text: "退稅商品、護照與收據要妥善保存；購物前確認店家是否提供免稅、商品是否需要密封，以及回程托運／手提限制。" },
    { title: "支付與網路", text: "交通 IC 卡、信用卡與現金分開準備；重要 QR code、住宿地址、航班與地圖截圖離線保存，避免完全依賴網路。" },
    { title: "天候與戶外行程", text: "嵐山、勝尾寺、USJ、京都御苑、保津川與臨空城都是戶外行程；十月中旬以短袖加薄外套分層，雨具、防滑鞋、替換襪放在隨身包。若 JMA 預報有雨、強風或警報，保津川遊船、交通與 USJ 以官方公告為準。" },
    { title: "每天晚上", text: "確認隔日第一班車、天氣、電量、現金、交通 IC 卡、票券 QR code 與集合時間。" },
    { title: "回程日", text: "退稅、托運、安檢與登機時間要分開預留；不同旅客的航班不要共用同一個離場時間。" }
  ],
  checklist: [
    { id: "passport", text: "護照／Visit Japan Web／入境資料" },
    { id: "tickets", text: "機票、住宿、JR／巴士／觀光列車票券" },
    { id: "usj", text: "USJ App、Studio Pass QR code、任天堂世界整理券／Express Pass" },
    { id: "power", text: "行動電源、充電線、轉接頭與離線截圖" },
    { id: "money", text: "日圓、信用卡、交通 IC 卡與備用現金" },
    { id: "weather", text: "薄外套、雨具、舒適步行鞋與替換襪（出發前看 JMA 7 日預報）" },
    { id: "medicine", text: "常備藥、處方箋／藥袋與個人用品" },
    { id: "luggage", text: "行李重量、退稅商品、液體與伴手禮空間" },
    { id: "contacts", text: "同行者聯絡方式、住宿地址、保險資料" },
    { id: "flight", text: "Emma／星宇、其他旅客／亞洲航空分開確認" }
  ],
  emergency: [
    { label: "日本警察", value: "110", action: "tel:110" },
    { label: "日本消防／救護車", value: "119", action: "tel:119" },
    { label: "日本外務省旅外安全", value: "安全資訊網站", action: "https://www.anzen.mofa.go.jp/" },
    { label: "駐大阪辦事處", value: "官方聯絡資料", action: "https://www.mofa.gov.tw/OverseasOffice_Content.aspx?n=168&os=85&s=142&sms=87" },
    { label: "住宿／保險／同行者", value: "請補上個人資料", action: "#" }
  ]
};
